import type { CropConfig, DiseaseRule, IrrigationMethod, PerennialYield, SeasonalYield } from "./types";

/**
 * The crop registry.
 *
 * READ THIS BEFORE TRUSTING A NUMBER HERE.
 *
 * Yield figures are conservative national ballparks, deliberately set nearer
 * the typical harvest than the headline one. Published "up to N quintals per
 * acre" figures are best-case demonstration plots; building them in would
 * inflate every farmer's revenue projection. Real yields swing by a factor of
 * three across variety, season, soil, spacing and management, so these are an
 * opening estimate the grower is expected to correct — see
 * Farm.expectedQtlPerAcre, which overrides all of this.
 *
 * Disease rules are only written where the pathogen genuinely follows the
 * "warm, wet, humid spell" shape this engine models. Powdery mildews (which
 * prefer dry weather) and insect pests (fall armyworm, fruit borer, tea
 * mosquito bug) do NOT fit it, and are deliberately absent rather than
 * shoehorned in. A crop can be economically important and still have no rule
 * here; that is honest, not incomplete.
 *
 * Everything below is pending review by an agronomist.
 */

const MONSOON = [6, 7, 8, 9, 10];
const RABI = [11, 12, 1, 2];

type Intervals = Record<IrrigationMethod, number>;

/** Water-hungry shallow-rooted vegetables. */
const VEG: Intervals = { drip: 2, sprinkler: 4, flood: 7, rainfed: Infinity };
/** Field crops and cereals. */
const FIELD: Intervals = { drip: 4, sprinkler: 7, flood: 10, rainfed: Infinity };
/** Deep-rooted orchard and plantation crops. */
const ORCHARD: Intervals = { drip: 4, sprinkler: 8, flood: 12, rainfed: Infinity };

function seasonal(qtlPerAcre: number, cycleDays: number): SeasonalYield {
  return { kind: "seasonal", qtlPerAcre, cycleDays };
}

function perennial(
  curve: { fromAge: number; qtlPerAcre: number }[],
  declineFromAge?: number,
  declinePerYear?: number,
): PerennialYield {
  return { kind: "perennial", curve, declineFromAge, declinePerYear };
}

/** Phytophthora rots share a shape: warm, soaked, humid, and Bordeaux answers them. */
function phytophthora(over: Partial<DiseaseRule> & Pick<DiseaseRule, "id" | "name">): DiseaseRule {
  return {
    pathogen: "Phytophthora spp.",
    months: MONSOON,
    humidityPct: 90,
    tempMinC: 20,
    tempMaxC: 30,
    wetDays: 3,
    treatment: {
      name: { en: "Bordeaux mixture 1%", kn: "ಬೋರ್ಡೊ ಮಿಶ್ರಣ ೧%" },
      dryHours: 6,
      protectionDays: 40,
    },
    lossShare: 0.3,
    ...over,
  };
}

/** A foliar fungus knocked back by a protectant spray on a short cycle. */
function foliar(
  id: string,
  en: string,
  kn: string,
  pathogen: string,
  band: { months: number[]; humidityPct: number; tempMinC: number; tempMaxC: number; wetDays: number },
  treatment: { en: string; kn: string; dryHours: number; protectionDays: number },
  lossShare: number,
): DiseaseRule {
  return {
    id,
    name: { en, kn },
    pathogen,
    ...band,
    treatment: {
      name: { en: treatment.en, kn: treatment.kn },
      dryHours: treatment.dryHours,
      protectionDays: treatment.protectionDays,
    },
    lossShare,
  };
}

const MANCOZEB = { en: "Mancozeb spray", kn: "ಮ್ಯಾಂಕೋಜೆಬ್ ಸಿಂಪರಣೆ" };
const COPPER = { en: "Copper oxychloride spray", kn: "ಕಾಪರ್ ಆಕ್ಸಿಕ್ಲೋರೈಡ್ ಸಿಂಪರಣೆ" };

export const CROPS: CropConfig[] = [
  // ---------------------------------------------------------------- plantation
  {
    id: "arecanut",
    name: { en: "Arecanut", hi: "सुपारी", kn: "ಅಡಿಕೆ", mr: "सुपारी" },
    agmarknetCommodity: "Arecanut(Betelnut/Supari)",
    grades: [
      { id: "rashi", label: { en: "Rashi", kn: "ರಾಶಿ" }, aliases: ["rashi", "raashi", "rashi idi"] },
      { id: "hosa_chali", label: { en: "Hosa Chali", kn: "ಹೊಸ ಚಾಲಿ" }, aliases: ["hosa chali", "hosachali", "new variety"] },
      { id: "hale_chali", label: { en: "Hale Chali", kn: "ಹಳೆ ಚಾಲಿ" }, aliases: ["hale chali", "halechali", "old variety"] },
      { id: "chippu", label: { en: "Chippu", kn: "ಚಿಪ್ಪು" }, aliases: ["chippu"] },
      { id: "bilegotu", label: { en: "Bilegotu", kn: "ಬಿಳೆಗೋಟು" }, aliases: ["bilegotu", "bile gotu"] },
      { id: "cqca", label: { en: "CQCA", kn: "ಸಿಕ್ಯುಸಿಎ" }, aliases: ["cqca", "c q c a"] },
    ],
    irrigation: { intervalDays: { drip: 3, sprinkler: 6, flood: 8, rainfed: Infinity }, rainSkipMm: 10 },
    yield: perennial([
      { fromAge: 5, qtlPerAcre: 2.7 },
      { fromAge: 6, qtlPerAcre: 4.5 },
      { fromAge: 7, qtlPerAcre: 6.8 },
      { fromAge: 8, qtlPerAcre: 9 },
    ], 40, 0.3),
    diseases: [phytophthora({ id: "koleroga", name: { en: "Koleroga (fruit rot)", kn: "ಕೊಳೆರೋಗ" }, pathogen: "Phytophthora meadii" })],
    notes: "Yellow Leaf Disease has no cure. Photograph yellowing fronds to build a per-block record.",
    yieldNote: "Chali basis, well-managed garden. Coastal gardens on good soil exceed this; diseased blocks fall far below.",
  },
  {
    id: "coconut",
    name: { en: "Coconut", hi: "नारियल", kn: "ತೆಂಗು", mr: "नारळ" },
    agmarknetCommodity: "Coconut",
    grades: [],
    irrigation: { intervalDays: { drip: 4, sprinkler: 7, flood: 10, rainfed: Infinity }, rainSkipMm: 12 },
    yield: perennial([
      { fromAge: 6, qtlPerAcre: 3 },
      { fromAge: 8, qtlPerAcre: 6 },
      { fromAge: 10, qtlPerAcre: 8 },
    ], 50, 0.2),
    diseases: [phytophthora({
      id: "bud_rot",
      name: { en: "Bud rot", kn: "ಸುಳಿ ಕೊಳೆ" },
      pathogen: "Phytophthora palmivora",
      treatment: { name: { en: "Bordeaux mixture 1% to the crown", kn: "ಸುಳಿಗೆ ಬೋರ್ಡೊ ಮಿಶ್ರಣ ೧%" }, dryHours: 6, protectionDays: 45 },
      lossShare: 0.25,
    })],
    yieldNote: "Agmarknet quotes coconut by weight, so this is a rough conversion from nut counts.",
  },
  {
    id: "copra",
    name: { en: "Copra", hi: "खोपरा", kn: "ಕೊಬ್ಬರಿ", mr: "खोबरे" },
    agmarknetCommodity: "Copra",
    grades: [],
    irrigation: { intervalDays: { drip: 4, sprinkler: 7, flood: 10, rainfed: Infinity }, rainSkipMm: 12 },
    yield: perennial([{ fromAge: 6, qtlPerAcre: 1.5 }, { fromAge: 8, qtlPerAcre: 3 }, { fromAge: 10, qtlPerAcre: 4 }], 50, 0.1),
    diseases: [phytophthora({ id: "copra_bud_rot", name: { en: "Bud rot", kn: "ಸುಳಿ ಕೊಳೆ" }, pathogen: "Phytophthora palmivora", lossShare: 0.25 })],
    yieldNote: "Dried kernel, roughly half the fresh nut weight of the same garden.",
  },
  {
    id: "black_pepper",
    name: { en: "Black pepper", hi: "काली मिर्च", kn: "ಕರಿಮೆಣಸು", mr: "काळी मिरी" },
    agmarknetCommodity: "Black pepper",
    grades: [],
    irrigation: { intervalDays: { drip: 4, sprinkler: 7, flood: 10, rainfed: Infinity }, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 3, qtlPerAcre: 0.8 }, { fromAge: 5, qtlPerAcre: 2 }, { fromAge: 7, qtlPerAcre: 2.8 }], 25, 0.1),
    diseases: [phytophthora({ id: "quick_wilt", name: { en: "Quick wilt (foot rot)", kn: "ಸೊರಗು ರೋಗ" }, pathogen: "Phytophthora capsici", wetDays: 2, lossShare: 0.4 })],
    yieldNote: "Dry pepper from vines on standards. Yield depends heavily on the standard tree and shade.",
  },
  {
    id: "cocoa",
    name: { en: "Cocoa", hi: "कोको", kn: "ಕೋಕೋ", mr: "कोको" },
    agmarknetCommodity: "Cocoa",
    grades: [],
    irrigation: { intervalDays: { drip: 4, sprinkler: 7, flood: 9, rainfed: Infinity }, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 3, qtlPerAcre: 1.2 }, { fromAge: 5, qtlPerAcre: 3 }, { fromAge: 7, qtlPerAcre: 4 }]),
    diseases: [phytophthora({
      id: "black_pod",
      name: { en: "Black pod", kn: "ಕಪ್ಪು ಕಾಯಿ ಕೊಳೆ" },
      pathogen: "Phytophthora palmivora",
      treatment: { name: { en: "Bordeaux mixture 1%", kn: "ಬೋರ್ಡೊ ಮಿಶ್ರಣ ೧%" }, dryHours: 5, protectionDays: 30 },
    })],
    yieldNote: "Dry bean, usually intercropped under arecanut or coconut.",
  },
  {
    id: "cardamom",
    name: { en: "Cardamom", hi: "इलायची", kn: "ಏಲಕ್ಕಿ", mr: "वेलची" },
    agmarknetCommodity: "Cardamoms",
    grades: [],
    irrigation: { intervalDays: { drip: 3, sprinkler: 6, flood: 9, rainfed: Infinity }, rainSkipMm: 12 },
    yield: perennial([{ fromAge: 2, qtlPerAcre: 0.2 }, { fromAge: 3, qtlPerAcre: 0.5 }, { fromAge: 5, qtlPerAcre: 0.7 }]),
    diseases: [phytophthora({ id: "capsule_rot", name: { en: "Capsule rot (azhukal)", kn: "ಕಾಯಿ ಕೊಳೆ" }, lossShare: 0.35 })],
    yieldNote: "Cured capsules. A very wide range in practice — shade-grown estates differ sharply from open plots.",
  },
  {
    id: "coffee",
    name: { en: "Coffee", hi: "कॉफ़ी", kn: "ಕಾಫಿ", mr: "कॉफी" },
    agmarknetCommodity: "Coffee",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 12 },
    yield: perennial([{ fromAge: 4, qtlPerAcre: 3 }, { fromAge: 6, qtlPerAcre: 6 }, { fromAge: 8, qtlPerAcre: 7 }], 30, 0.2),
    diseases: [foliar("leaf_rust", "Coffee leaf rust", "ಕಾಫಿ ತುಕ್ಕು ರೋಗ", "Hemileia vastatrix",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 28, wetDays: 3 },
      { ...COPPER, dryHours: 5, protectionDays: 45 }, 0.25)],
    yieldNote: "Clean coffee. Arabica typically yields below robusta on the same acreage.",
  },
  {
    id: "cashew",
    name: { en: "Cashew", hi: "काजू", kn: "ಗೋಡಂಬಿ", mr: "काजू" },
    agmarknetCommodity: "Cashewnuts",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 12 },
    yield: perennial([{ fromAge: 4, qtlPerAcre: 2 }, { fromAge: 6, qtlPerAcre: 4 }, { fromAge: 8, qtlPerAcre: 5 }], 25, 0.15),
    diseases: [foliar("cashew_anthracnose", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum gloeosporioides", { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 3 }, { ...COPPER, dryHours: 5, protectionDays: 21 }, 0.25)],
    notes: "The main cashew problem is tea mosquito bug, an insect pest. This app only models weather-driven diseases, so it will not warn you about it.",
    yieldNote: "Raw nut. Grafted varieties outyield seedling trees substantially.",
  },

  // ---------------------------------------------------------------- fruit
  {
    id: "grapes",
    name: { en: "Grapes", hi: "अंगूर", kn: "ದ್ರಾಕ್ಷಿ", mr: "द्राक्ष" },
    agmarknetCommodity: "Grapes",
    grades: [],
    irrigation: { intervalDays: { drip: 2, sprinkler: 5, flood: 9, rainfed: Infinity }, rainSkipMm: 8 },
    yield: perennial([{ fromAge: 3, qtlPerAcre: 40 }, { fromAge: 4, qtlPerAcre: 80 }, { fromAge: 6, qtlPerAcre: 100 }], 18, 4),
    diseases: [foliar("downy_mildew", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Plasmopara viticola",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 27, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 10 }, 0.45)],
    notes: "Powdery mildew is the other major grape disease, but it spreads in dry weather, so this app's wet-spell rules will not catch it.",
    yieldNote: "Table grapes on a well-managed trellis. Raisin varieties and young vines yield considerably less.",
  },
  {
    id: "mango",
    name: { en: "Mango", hi: "आम", kn: "ಮಾವು", mr: "आंबा" },
    agmarknetCommodity: "Mango",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 12 },
    yield: perennial([{ fromAge: 5, qtlPerAcre: 8 }, { fromAge: 8, qtlPerAcre: 20 }, { fromAge: 12, qtlPerAcre: 30 }], 40, 0.5),
    diseases: [foliar("anthracnose", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum gloeosporioides",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 3 },
      { ...COPPER, dryHours: 5, protectionDays: 21 }, 0.3)],
    notes: "Mango alternates: a heavy year is usually followed by a light one, which this estimate does not model.",
    yieldNote: "Mature orchard average across on and off years.",
  },
  {
    id: "pomegranate",
    name: { en: "Pomegranate", hi: "अनार", kn: "ದಾಳಿಂಬೆ", mr: "डाळिंब" },
    agmarknetCommodity: "Pomegranate",
    grades: [],
    irrigation: { intervalDays: { drip: 3, sprinkler: 6, flood: 10, rainfed: Infinity }, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 3, qtlPerAcre: 20 }, { fromAge: 5, qtlPerAcre: 45 }, { fromAge: 7, qtlPerAcre: 55 }], 15, 3),
    diseases: [foliar("bacterial_blight", "Bacterial blight (telya)", "ತೆಲ್ಯಾ ರೋಗ", "Xanthomonas axonopodis",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 32, wetDays: 2 },
      { en: "Copper oxychloride + streptocycline", kn: "ಕಾಪರ್ ಆಕ್ಸಿಕ್ಲೋರೈಡ್ + ಸ್ಟ್ರೆಪ್ಟೊಸೈಕ್ಲಿನ್", dryHours: 4, protectionDays: 14 }, 0.5)],
    yieldNote: "Telya can take an entire orchard, so realised yields vary far more than this figure suggests.",
  },
  {
    id: "banana",
    name: { en: "Banana", hi: "केला", kn: "ಬಾಳೆ", mr: "केळी" },
    agmarknetCommodity: "Banana",
    grades: [],
    irrigation: { intervalDays: { drip: 2, sprinkler: 4, flood: 7, rainfed: Infinity }, rainSkipMm: 10 },
    yield: seasonal(120, 330),
    diseases: [foliar("sigatoka", "Sigatoka leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Mycosphaerella spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 32, wetDays: 3 },
      { en: "Propiconazole spray", kn: "ಪ್ರೊಪಿಕೊನಜೋಲ್ ಸಿಂಪರಣೆ", dryHours: 5, protectionDays: 30 }, 0.25)],
    yieldNote: "One full crop cycle at commercial spacing.",
  },
  {
    id: "sapota",
    name: { en: "Sapota", hi: "चीकू", kn: "ಸಪೋಟ", mr: "चिकू" },
    agmarknetCommodity: "Sapota",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 12 },
    yield: perennial([{ fromAge: 5, qtlPerAcre: 20 }, { fromAge: 8, qtlPerAcre: 45 }, { fromAge: 12, qtlPerAcre: 60 }], 40, 0.6),
    diseases: [foliar("sapota_leaf_spot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Phaeophleospora indica", { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 32, wetDays: 3 }, { ...MANCOZEB, dryHours: 4, protectionDays: 21 }, 0.2)],
    yieldNote: "Mature orchard. Bears over a long season rather than one harvest.",
  },
  {
    id: "papaya",
    name: { en: "Papaya", hi: "पपीता", kn: "ಪಪ್ಪಾಯಿ", mr: "पपई" },
    agmarknetCommodity: "Papaya",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 1, qtlPerAcre: 150 }, { fromAge: 2, qtlPerAcre: 250 }], 3, 80),
    diseases: [foliar("papaya_anthracnose", "Anthracnose (fruit rot)", "ಹಣ್ಣು ಕೊಳೆ ರೋಗ", "Colletotrichum gloeosporioides", { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 2 }, { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    notes: "Papaya ring spot is a virus spread by aphids, not weather, so no spray window is offered for it.",
    yieldNote: "Heaviest in the second year, then falls away sharply — most growers replant after three.",
  },
  {
    id: "watermelon",
    name: { en: "Watermelon", hi: "तरबूज", kn: "ಕಲ್ಲಂಗಡಿ", mr: "कलिंगड" },
    agmarknetCommodity: "Water Melon",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(110, 90),
    diseases: [foliar("melon_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora cubensis", { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 }, { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Summer crop on drip with mulch. Open flood-irrigated plots yield well below this.",
  },

  // ---------------------------------------------------------------- vegetables
  {
    id: "tomato",
    name: { en: "Tomato", hi: "टमाटर", kn: "ಟೊಮೇಟೊ", mr: "टोमॅटो" },
    agmarknetCommodity: "Tomato",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(90, 100),
    diseases: [foliar("late_blight", "Late blight", "ಅಂಗಮಾರಿ ರೋಗ", "Phytophthora infestans",
      { months: [6, 7, 8, 9, 10, 11, 12], humidityPct: 88, tempMinC: 12, tempMaxC: 25, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 10 }, 0.5)],
    yieldNote: "Hybrid on stakes. Open-pollinated varieties give roughly half this.",
  },
  {
    id: "onion",
    name: { en: "Onion", hi: "प्याज़", kn: "ಈರುಳ್ಳಿ", mr: "कांदा" },
    agmarknetCommodity: "Onion",
    grades: [],
    irrigation: { intervalDays: { drip: 3, sprinkler: 6, flood: 10, rainfed: Infinity }, rainSkipMm: 8 },
    yield: seasonal(100, 120),
    diseases: [foliar("purple_blotch", "Purple blotch", "ನೇರಳೆ ಮಚ್ಚೆ ರೋಗ", "Alternaria porri",
      { months: MONSOON, humidityPct: 80, tempMinC: 21, tempMaxC: 32, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 12 }, 0.35)],
    notes: "Onion needs a sticker with the spray — the leaves shed plain water.",
    yieldNote: "Rabi crop. Kharif onion typically yields a fifth to a third less.",
  },
  {
    id: "potato",
    name: { en: "Potato", hi: "आलू", kn: "ಆಲೂಗಡ್ಡೆ", mr: "बटाटा" },
    agmarknetCommodity: "Potato",
    grades: [],
    irrigation: { intervalDays: { drip: 3, sprinkler: 5, flood: 8, rainfed: Infinity }, rainSkipMm: 8 },
    yield: seasonal(80, 100),
    diseases: [foliar("potato_late_blight", "Late blight", "ಅಂಗಮಾರಿ ರೋಗ", "Phytophthora infestans",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 22, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 10 }, 0.5)],
    yieldNote: "Cool-season crop on good seed. Late blight in a wet December can halve it.",
  },
  {
    id: "green_chilli",
    name: { en: "Green chilli", hi: "हरी मिर्च", kn: "ಹಸಿಮೆಣಸಿನಕಾಯಿ", mr: "हिरवी मिरची" },
    agmarknetCommodity: "Green Chilli",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(60, 150),
    diseases: [foliar("chilli_anthracnose", "Fruit rot (anthracnose)", "ಹಣ್ಣು ಕೊಳೆ ರೋಗ", "Colletotrichum capsici",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 12 }, 0.4)],
    notes: "Leaf curl from thrips and mites causes more loss than any fungus in many seasons, and is not modelled here.",
    yieldNote: "Green harvest across multiple pickings. Dry chilli is roughly a quarter of this weight.",
  },
  {
    id: "brinjal",
    name: { en: "Brinjal", hi: "बैंगन", kn: "ಬದನೆಕಾಯಿ", mr: "वांगे" },
    agmarknetCommodity: "Brinjal",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(100, 150),
    diseases: [foliar("phomopsis", "Phomopsis blight (fruit rot)", "ಹಣ್ಣು ಕೊಳೆ ರೋಗ", "Phomopsis vexans", { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 32, wetDays: 2 }, { ...MANCOZEB, dryHours: 4, protectionDays: 12 }, 0.3)],
    notes: "Shoot and fruit borer is the main brinjal problem. It is an insect, so this app offers no spray window for it.",
    yieldNote: "Across the full picking season, not a single harvest.",
  },
  {
    id: "bhindi",
    name: { en: "Okra", hi: "भिंडी", kn: "ಬೆಂಡೆಕಾಯಿ", mr: "भेंडी" },
    agmarknetCommodity: "Bhindi(Ladies Finger)",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(50, 120),
    diseases: [foliar("okra_leaf_spot", "Cercospora leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora abelmoschi", { months: MONSOON, humidityPct: 85, tempMinC: 20, tempMaxC: 32, wetDays: 3 }, { ...MANCOZEB, dryHours: 4, protectionDays: 12 }, 0.2)],
    notes: "Yellow vein mosaic is a whitefly-borne virus; controlling the whitefly matters more than any fungicide.",
    yieldNote: "Total across pickings.",
  },
  {
    id: "cabbage",
    name: { en: "Cabbage", hi: "पत्ता गोभी", kn: "ಎಲೆಕೋಸು", mr: "कोबी" },
    agmarknetCommodity: "Cabbage",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(100, 90),
    diseases: [foliar("black_rot", "Black rot", "ಕಪ್ಪು ಕೊಳೆ ರೋಗ", "Xanthomonas campestris", { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 32, wetDays: 2 }, { ...COPPER, dryHours: 4, protectionDays: 12 }, 0.35)],
    yieldNote: "Heads at commercial spacing.",
  },
  {
    id: "cauliflower",
    name: { en: "Cauliflower", hi: "फूल गोभी", kn: "ಹೂಕೋಸು", mr: "फ्लॉवर" },
    agmarknetCommodity: "Cauliflower",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(80, 90),
    diseases: [foliar("crucifer_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Peronospora parasitica", { months: RABI, humidityPct: 88, tempMinC: 8, tempMaxC: 22, wetDays: 2 }, { ...MANCOZEB, dryHours: 4, protectionDays: 12 }, 0.3)],
    yieldNote: "Curd weight. Very sensitive to sowing date — a late crop can fail to head at all.",
  },
  {
    id: "carrot",
    name: { en: "Carrot", hi: "गाजर", kn: "ಕ್ಯಾರೆಟ್", mr: "गाजर" },
    agmarknetCommodity: "Carrot",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(70, 100),
    diseases: [foliar("carrot_blight", "Alternaria leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria dauci", { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 30, wetDays: 3 }, { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Needs deep loose soil; heavy soils give forked roots and lower marketable yield.",
  },
  {
    id: "cucumber",
    name: { en: "Cucumber", hi: "खीरा", kn: "ಸೌತೆಕಾಯಿ", mr: "काकडी" },
    agmarknetCommodity: "Cucumbar(Kheera)",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(70, 70),
    diseases: [foliar("cucurbit_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora cubensis",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.4)],
    yieldNote: "Across pickings on a short cycle.",
  },
  {
    id: "beans",
    name: { en: "Beans", hi: "सेम", kn: "ಹುರುಳಿಕಾಯಿ", mr: "घेवडा" },
    agmarknetCommodity: "Beans",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(35, 90),
    diseases: [foliar("bean_anthracnose", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum lindemuthianum", { months: MONSOON, humidityPct: 88, tempMinC: 15, tempMaxC: 26, wetDays: 2 }, { ...MANCOZEB, dryHours: 4, protectionDays: 12 }, 0.3)],
    yieldNote: "Green pods across pickings. Pole types outyield bush types.",
  },

  // ---------------------------------------------------------------- field crops
  {
    id: "paddy",
    name: { en: "Paddy", hi: "धान", kn: "ಭತ್ತ", mr: "भात" },
    agmarknetCommodity: "Paddy(Dhan)(Common)",
    grades: [],
    irrigation: { intervalDays: { drip: 5, sprinkler: 5, flood: 4, rainfed: Infinity }, rainSkipMm: 15 },
    yield: seasonal(20, 125),
    diseases: [foliar("blast", "Rice blast", "ಬೆಂಕಿ ರೋಗ", "Pyricularia oryzae",
      { months: [7, 8, 9, 10, 11], humidityPct: 90, tempMinC: 20, tempMaxC: 28, wetDays: 2 },
      { en: "Tricyclazole spray", kn: "ಟ್ರೈಸೈಕ್ಲಜೋಲ್ ಸಿಂಪರಣೆ", dryHours: 4, protectionDays: 21 }, 0.3)],
    yieldNote: "Irrigated crop. Rainfed paddy commonly yields half this.",
  },
  {
    id: "ragi",
    name: { en: "Ragi", hi: "रागी", kn: "ರಾಗಿ", mr: "नाचणी" },
    agmarknetCommodity: "Ragi (Finger Millet)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 12 },
    yield: seasonal(12, 110),
    diseases: [foliar("ragi_blast", "Finger blast", "ಬೆಂಕಿ ರೋಗ", "Pyricularia grisea",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { en: "Carbendazim spray", kn: "ಕಾರ್ಬೆಂಡಜಿಮ್ ಸಿಂಪರಣೆ", dryHours: 4, protectionDays: 20 }, 0.3)],
    yieldNote: "Mostly grown rainfed in Karnataka; irrigated plots do better.",
  },
  {
    id: "maize",
    name: { en: "Maize", hi: "मक्का", kn: "ಮೆಕ್ಕೆಜೋಳ", mr: "मका" },
    agmarknetCommodity: "Maize",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 12 },
    yield: seasonal(25, 100),
    diseases: [foliar("turcicum", "Turcicum leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Exserohilum turcicum",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 28, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    notes: "Fall armyworm is the bigger threat in most seasons and is an insect, so no spray window is given for it.",
    yieldNote: "Hybrid grain at 14% moisture.",
  },
  {
    id: "jowar",
    name: { en: "Jowar", hi: "ज्वार", kn: "ಜೋಳ", mr: "ज्वारी" },
    agmarknetCommodity: "Jowar(Sorghum)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 12 },
    yield: seasonal(12, 110),
    diseases: [foliar("grain_mould", "Grain mould", "ಕಾಳು ಬೂಷ್ಟು", "Fusarium spp.", { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 3 }, { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.3)],
    yieldNote: "Grain only. Rabi jowar on residual moisture yields less than the kharif crop.",
  },
  {
    id: "wheat",
    name: { en: "Wheat", hi: "गेहूँ", kn: "ಗೋಧಿ", mr: "गहू" },
    agmarknetCommodity: "Wheat",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 12 },
    yield: seasonal(18, 120),
    diseases: [foliar("yellow_rust", "Yellow rust", "ಹಳದಿ ತುಕ್ಕು", "Puccinia striiformis",
      { months: RABI, humidityPct: 80, tempMinC: 5, tempMaxC: 18, wetDays: 2 },
      { en: "Propiconazole spray", kn: "ಪ್ರೊಪಿಕೊನಜೋಲ್ ಸಿಂಪರಣೆ", dryHours: 4, protectionDays: 21 }, 0.3)],
    yieldNote: "Irrigated crop with full fertiliser.",
  },
  {
    id: "groundnut",
    name: { en: "Groundnut", hi: "मूंगफली", kn: "ಕಡಲೆಕಾಯಿ", mr: "भुईमूग" },
    agmarknetCommodity: "Groundnut",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(10, 110),
    diseases: [foliar("late_leaf_spot", "Late leaf spot (tikka)", "ಟಿಕ್ಕಾ ರೋಗ", "Phaeoisariopsis personata",
      { months: MONSOON, humidityPct: 85, tempMinC: 20, tempMaxC: 30, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.3)],
    yieldNote: "Dry pods. Published figures of 20-25 qtl/acre are demonstration plots, not field averages.",
  },
  {
    id: "sunflower",
    name: { en: "Sunflower", hi: "सूरजमुखी", kn: "ಸೂರ್ಯಕಾಂತಿ", mr: "सूर्यफूल" },
    agmarknetCommodity: "Sunflower",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(6, 100),
    diseases: [foliar("sunflower_blight", "Alternaria leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria helianthi", { months: MONSOON, humidityPct: 85, tempMinC: 20, tempMaxC: 30, wetDays: 3 }, { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Seed. Birds take a meaningful share in small plots.",
  },
  {
    id: "soyabean",
    name: { en: "Soyabean", hi: "सोयाबीन", kn: "ಸೋಯಾಬೀನ್", mr: "सोयाबीन" },
    agmarknetCommodity: "Soyabean",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 12 },
    yield: seasonal(10, 100),
    diseases: [foliar("soy_rust", "Soybean rust", "ತುಕ್ಕು ರೋಗ", "Phakopsora pachyrhizi", { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 28, wetDays: 3 }, { en: "Propiconazole spray", kn: "ಪ್ರೊಪಿಕೊನಜೋಲ್ ಸಿಂಪರಣೆ", dryHours: 4, protectionDays: 21 }, 0.3)],
    yieldNote: "Grain, largely rainfed.",
  },
  {
    id: "tur",
    name: { en: "Tur / red gram", hi: "अरहर", kn: "ತೊಗರಿ", mr: "तूर" },
    agmarknetCommodity: "Arhar (Tur/Red Gram)(Whole)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 12 },
    yield: seasonal(6, 180),
    diseases: [phytophthora({ id: "tur_blight", name: { en: "Phytophthora blight", kn: "ಫೈಟೊಫ್ಥೊರಾ ಅಂಗಮಾರಿ" }, wetDays: 3, treatment: { name: { ...MANCOZEB }, dryHours: 4, protectionDays: 21 }, lossShare: 0.25 })],
    notes: "Pod borer decides most tur harvests, and it is an insect pest this app does not model.",
    yieldNote: "Long-duration crop, usually rainfed.",
  },
  {
    id: "bengal_gram",
    name: { en: "Bengal gram", hi: "चना", kn: "ಕಡಲೆ", mr: "हरभरा" },
    agmarknetCommodity: "Bengal Gram(Gram)(Whole)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 12 },
    yield: seasonal(8, 110),
    diseases: [foliar("ascochyta", "Ascochyta blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Ascochyta rabiei", { months: RABI, humidityPct: 85, tempMinC: 10, tempMaxC: 25, wetDays: 2 }, { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.3)],
    yieldNote: "Rabi crop, often on residual moisture.",
  },
  {
    id: "green_gram",
    name: { en: "Green gram", hi: "मूंग", kn: "ಹೆಸರುಕಾಳು", mr: "मूग" },
    agmarknetCommodity: "Green Gram (Moong)(Whole)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(4, 70),
    diseases: [foliar("moong_leaf_spot", "Cercospora leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora canescens", { months: MONSOON, humidityPct: 85, tempMinC: 20, tempMaxC: 32, wetDays: 3 }, { ...MANCOZEB, dryHours: 4, protectionDays: 12 }, 0.25)],
    yieldNote: "Short-duration pulse, commonly grown as a catch crop.",
  },
  {
    id: "cotton",
    name: { en: "Cotton", hi: "कपास", kn: "ಹತ್ತಿ", mr: "कापूस" },
    agmarknetCommodity: "Cotton",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 12 },
    yield: seasonal(10, 180),
    diseases: [foliar("cotton_blight", "Bacterial blight", "ಬ್ಯಾಕ್ಟೀರಿಯಾ ಅಂಗಮಾರಿ", "Xanthomonas citri pv. malvacearum", { months: MONSOON, humidityPct: 88, tempMinC: 22, tempMaxC: 34, wetDays: 2 }, { ...COPPER, dryHours: 4, protectionDays: 15 }, 0.25)],
    notes: "Pink bollworm governs cotton returns and is an insect pest, so no spray window is offered.",
    yieldNote: "Seed cotton (kapas), not lint.",
  },
  {
    id: "sugarcane",
    name: { en: "Sugarcane", hi: "गन्ना", kn: "ಕಬ್ಬು", mr: "ऊस" },
    agmarknetCommodity: "Sugarcane",
    grades: [],
    irrigation: { intervalDays: { drip: 4, sprinkler: 8, flood: 12, rainfed: Infinity }, rainSkipMm: 15 },
    yield: seasonal(350, 365),
    diseases: [foliar("cane_rust", "Cane rust", "ಕಬ್ಬು ತುಕ್ಕು", "Puccinia melanocephala", { months: MONSOON, humidityPct: 85, tempMinC: 20, tempMaxC: 30, wetDays: 3 }, { en: "Propiconazole spray", kn: "ಪ್ರೊಪಿಕೊನಜೋಲ್ ಸಿಂಪರಣೆ", dryHours: 5, protectionDays: 30 }, 0.2)],
    notes: "Red rot is managed by choosing resistant setts, not by spraying, so no spray window applies.",
    yieldNote: "Cane weight over a full twelve-month crop. Ratoon crops yield less than plant cane.",
  },
  {
    id: "turmeric",
    name: { en: "Turmeric", hi: "हल्दी", kn: "ಅರಿಶಿನ", mr: "हळद" },
    agmarknetCommodity: "Turmeric",
    grades: [],
    irrigation: { intervalDays: { drip: 3, sprinkler: 6, flood: 9, rainfed: Infinity }, rainSkipMm: 12 },
    yield: seasonal(80, 240),
    diseases: [foliar("rhizome_rot", "Rhizome rot", "ಗಡ್ಡೆ ಕೊಳೆ ರೋಗ", "Pythium spp.",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 32, wetDays: 4 },
      { en: "Metalaxyl + mancozeb drench", kn: "ಮೆಟಲಾಕ್ಸಿಲ್ + ಮ್ಯಾಂಕೋಜೆಬ್ ಡ್ರೆಂಚ್", dryHours: 3, protectionDays: 30 }, 0.35)],
    yieldNote: "Fresh rhizome. Dry turmeric is roughly a fifth of this weight.",
  },
  {
    id: "ginger",
    name: { en: "Ginger", hi: "अदरक", kn: "ಶುಂಠಿ", mr: "आले" },
    agmarknetCommodity: "Ginger(Green)",
    grades: [],
    irrigation: { intervalDays: { drip: 3, sprinkler: 6, flood: 9, rainfed: Infinity }, rainSkipMm: 12 },
    yield: seasonal(70, 240),
    diseases: [foliar("soft_rot", "Soft rot", "ಮೃದು ಕೊಳೆ ರೋಗ", "Pythium aphanidermatum",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 32, wetDays: 4 },
      { en: "Metalaxyl + mancozeb drench", kn: "ಮೆಟಲಾಕ್ಸಿಲ್ + ಮ್ಯಾಂಕೋಜೆಬ್ ಡ್ರೆಂಚ್", dryHours: 3, protectionDays: 30 }, 0.4)],
    notes: "Soft rot follows waterlogging. Drainage matters more than any drench.",
    yieldNote: "Fresh rhizome.",
  },

  // ---------------------------------------------------------------- wider India
  {
    id: "bajra",
    name: { en: "Bajra", hi: "बाजरा", kn: "ಸಜ್ಜೆ", mr: "बाजरी" },
    agmarknetCommodity: "Bajra(Pearl Millet/Cumbu)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(10, 90),
    diseases: [foliar("bajra_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Rainfed kharif grain.",
  },
  {
    id: "barley",
    name: { en: "Barley", hi: "जौ", kn: "ಬಾರ್ಲಿ", mr: "सातू" },
    agmarknetCommodity: "Barley (Jau)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(15, 120),
    diseases: [foliar("barley_rrust", "Rust", "ತುಕ್ಕು ರೋಗ", "Puccinia spp.",
      { months: RABI, humidityPct: 80, tempMinC: 5, tempMaxC: 20, wetDays: 2 },
      { en: "Propiconazole spray", kn: "ಪ್ರೊಪಿಕೊನಜೋಲ್ ಸಿಂಪರಣೆ", dryHours: 4, protectionDays: 21 }, 0.25)],
    yieldNote: "Irrigated rabi grain.",
  },
  {
    id: "foxtail_millet",
    name: { en: "Foxtail millet", hi: "कंगनी", kn: "ನವಣೆ", mr: "राळा" },
    agmarknetCommodity: "Foxtail Millet(Navane)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(8, 80),
    diseases: [foliar("foxtail_millet_blight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 30, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rainfed minor millet.",
  },
  {
    id: "kodo_millet",
    name: { en: "Kodo millet", hi: "कोदो", kn: "ಹಾರಕ", mr: "कोद्रा" },
    agmarknetCommodity: "Kodo Millet(Varagu)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(7, 110),
    diseases: [foliar("kodo_millet_blight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 30, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rainfed minor millet.",
  },
  {
    id: "little_millet",
    name: { en: "Little millet", hi: "कुटकी", kn: "ಸಾಮೆ", mr: "वरी" },
    agmarknetCommodity: "Little Millet (Kutki)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(6, 90),
    diseases: [foliar("little_millet_blight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 30, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rainfed minor millet.",
  },
  {
    id: "oats",
    name: { en: "Oats", hi: "जई", kn: "ಓಟ್ಸ್", mr: "ओट" },
    agmarknetCommodity: "Oat",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(12, 110),
    diseases: [foliar("oats_rrust", "Rust", "ತುಕ್ಕು ರೋಗ", "Puccinia spp.",
      { months: RABI, humidityPct: 80, tempMinC: 5, tempMaxC: 20, wetDays: 2 },
      { en: "Propiconazole spray", kn: "ಪ್ರೊಪಿಕೊನಜೋಲ್ ಸಿಂಪರಣೆ", dryHours: 4, protectionDays: 21 }, 0.25)],
    yieldNote: "Mostly grown as fodder.",
  },
  {
    id: "urad",
    name: { en: "Urad / black gram", hi: "उड़द", kn: "ಉದ್ದು", mr: "उडीद" },
    agmarknetCommodity: "Black Gram (Urd Beans)(Whole)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(4, 80),
    diseases: [foliar("urad_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Short-duration pulse.",
  },
  {
    id: "lentil",
    name: { en: "Lentil / masoor", hi: "मसूर", kn: "ಮಸೂರ್", mr: "मसूर" },
    agmarknetCommodity: "Lentil (Masur)(Whole)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(6, 110),
    diseases: [foliar("lentil_rblight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 24, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rabi pulse on residual moisture.",
  },
  {
    id: "horse_gram",
    name: { en: "Horse gram", hi: "कुल्थी", kn: "ಹುರುಳಿ", mr: "कुळीथ" },
    agmarknetCommodity: "Horse Gram",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(4, 100),
    diseases: [foliar("horse_gram_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Hardy rainfed pulse.",
  },
  {
    id: "cowpea",
    name: { en: "Cowpea", hi: "लोबिया", kn: "ಅಲಸಂದೆ", mr: "चवळी" },
    agmarknetCommodity: "Cowpea(Veg)",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(30, 75),
    diseases: [foliar("cowpea_anthrac", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    yieldNote: "Green pods across pickings.",
  },
  {
    id: "field_pea",
    name: { en: "Field pea", hi: "मटर", kn: "ಬಟಾಣಿ", mr: "वाटाणा" },
    agmarknetCommodity: "Peas(Dry)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(8, 110),
    diseases: [foliar("field_pea_rblight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 24, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rabi pulse.",
  },
  {
    id: "moth_bean",
    name: { en: "Moth bean", hi: "मोठ", kn: "ಮಟಕಿ", mr: "मटकी" },
    agmarknetCommodity: "Math",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(3, 75),
    diseases: [foliar("moth_bean_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Arid-zone pulse.",
  },
  {
    id: "rajma",
    name: { en: "Rajma", hi: "राजमा", kn: "ರಾಜ್ಮಾ", mr: "राजमा" },
    agmarknetCommodity: "Rajmash",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(8, 120),
    diseases: [foliar("rajma_anthrac", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    yieldNote: "Hill and rabi crop.",
  },
  {
    id: "green_peas",
    name: { en: "Green peas", hi: "हरी मटर", kn: "ಹಸಿ ಬಟಾಣಿ", mr: "हिरवे वाटाणे" },
    agmarknetCommodity: "Peas Wet",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(40, 100),
    diseases: [foliar("green_peas_rblight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 24, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Green pods, single season.",
  },
  {
    id: "cluster_beans",
    name: { en: "Cluster beans", hi: "ग्वार", kn: "ಗೋರಿಕಾಯಿ", mr: "गवार" },
    agmarknetCommodity: "Cluster beans",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(30, 90),
    diseases: [foliar("cluster_beans_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Green pods across pickings.",
  },
  {
    id: "mustard",
    name: { en: "Mustard", hi: "सरसों", kn: "ಸಾಸಿವೆ", mr: "मोहरी" },
    agmarknetCommodity: "Mustard",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(7, 120),
    diseases: [foliar("mustard_rblight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 24, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rabi oilseed.",
  },
  {
    id: "sesamum",
    name: { en: "Sesamum", hi: "तिल", kn: "ಎಳ್ಳು", mr: "तीळ" },
    agmarknetCommodity: "Sesamum(Sesame,Gingelly,Til)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(3, 90),
    diseases: [foliar("sesamum_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Largely rainfed.",
  },
  {
    id: "castor",
    name: { en: "Castor", hi: "अरंडी", kn: "ಹರಳು", mr: "एरंड" },
    agmarknetCommodity: "Castor Seed",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(8, 150),
    diseases: [foliar("castor_blight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 30, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Long-duration rainfed oilseed.",
  },
  {
    id: "safflower",
    name: { en: "Safflower", hi: "कुसुम", kn: "ಕುಸುಬೆ", mr: "करडई" },
    agmarknetCommodity: "Safflower",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(5, 130),
    diseases: [foliar("safflower_rblight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 24, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rabi on residual moisture.",
  },
  {
    id: "niger",
    name: { en: "Niger", hi: "रामतिल", kn: "ಗುರೆಳ್ಳು", mr: "खुरासणी" },
    agmarknetCommodity: "Niger Seed (Ramtil)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(2, 100),
    diseases: [foliar("niger_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Tribal and rainfed tracts.",
  },
  {
    id: "linseed",
    name: { en: "Linseed", hi: "अलसी", kn: "ಅಗಸೆ", mr: "जवस" },
    agmarknetCommodity: "Linseed",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(5, 120),
    diseases: [foliar("linseed_rrust", "Rust", "ತುಕ್ಕು ರೋಗ", "Puccinia spp.",
      { months: RABI, humidityPct: 80, tempMinC: 5, tempMaxC: 20, wetDays: 2 },
      { en: "Propiconazole spray", kn: "ಪ್ರೊಪಿಕೊನಜೋಲ್ ಸಿಂಪರಣೆ", dryHours: 4, protectionDays: 21 }, 0.25)],
    yieldNote: "Rabi oilseed.",
  },
  {
    id: "jute",
    name: { en: "Jute", hi: "जूट", kn: "ಸೆಣಬು", mr: "ताग" },
    agmarknetCommodity: "Jute",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(25, 120),
    diseases: [foliar("jute_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Fibre, eastern India.",
  },
  {
    id: "tobacco",
    name: { en: "Tobacco", hi: "तंबाकू", kn: "ಹೊಗೆಸೊಪ್ಪು", mr: "तंबाखू" },
    agmarknetCommodity: "Tobacco",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(8, 120),
    diseases: [foliar("tobacco_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Cured leaf.",
  },
  {
    id: "tea",
    name: { en: "Tea", hi: "चाय", kn: "ಚಹಾ", mr: "चहा" },
    agmarknetCommodity: "Tea",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 4, qtlPerAcre: 4 }, { fromAge: 6, qtlPerAcre: 8 }, { fromAge: 8, qtlPerAcre: 10 }], 50, 0.2),
    diseases: [foliar("tea_blight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 30, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Made tea across many pluckings.",
  },
  {
    id: "rubber",
    name: { en: "Rubber", hi: "रबर", kn: "ರಬ್ಬರ್", mr: "रबर" },
    agmarknetCommodity: "Rubber",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 7, qtlPerAcre: 4 }, { fromAge: 10, qtlPerAcre: 7 }, { fromAge: 14, qtlPerAcre: 9 }], 30, 0.2),
    diseases: [foliar("rubber_phyto", "Phytophthora rot", "ಫೈಟೊಫ್ಥೊರಾ ಕೊಳೆ", "Phytophthora spp.",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 3 },
      { ...COPPER, dryHours: 5, protectionDays: 30 }, 0.3)],
    yieldNote: "Dry rubber sheet. Abnormal leaf fall is the monsoon threat.",
  },
  {
    id: "oil_palm",
    name: { en: "Oil palm", hi: "तेल ताड़", kn: "ಎಣ್ಣೆ ತಾಳೆ", mr: "तेल माड" },
    agmarknetCommodity: "Oil Palm",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 4, qtlPerAcre: 20 }, { fromAge: 7, qtlPerAcre: 60 }, { fromAge: 10, qtlPerAcre: 90 }], 30, 2),
    diseases: [foliar("oil_palm_phyto", "Phytophthora rot", "ಫೈಟೊಫ್ಥೊರಾ ಕೊಳೆ", "Phytophthora spp.",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 3 },
      { ...COPPER, dryHours: 5, protectionDays: 30 }, 0.3)],
    yieldNote: "Fresh fruit bunches.",
  },
  {
    id: "dry_chilli",
    name: { en: "Dry chilli", hi: "सूखी मिर्च", kn: "ಒಣ ಮೆಣಸಿನಕಾಯಿ", mr: "लाल मिरची" },
    agmarknetCommodity: "Dry Chillies",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(15, 180),
    diseases: [foliar("dry_chilli_anthrac", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    yieldNote: "Dry pods, roughly a quarter of green weight.",
  },
  {
    id: "coriander_seed",
    name: { en: "Coriander seed", hi: "धनिया", kn: "ಕೊತ್ತಂಬರಿ ಬೀಜ", mr: "धणे" },
    agmarknetCommodity: "Coriander(Leaves)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(6, 110),
    diseases: [foliar("coriander_seed_rblight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 24, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rabi seed crop.",
  },
  {
    id: "coriander_leaves",
    name: { en: "Coriander leaves", hi: "धनिया", kn: "ಕೊತ್ತಂಬರಿ ಸೊಪ್ಪು", mr: "कोथिंबीर" },
    agmarknetCommodity: "Coriander(Leaves)",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(25, 45),
    diseases: [foliar("coriander_leaves_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Leafy crop, short cycle.",
  },
  {
    id: "cumin",
    name: { en: "Cumin", hi: "जीरा", kn: "ಜೀರಿಗೆ", mr: "जिरे" },
    agmarknetCommodity: "Cummin Seed(Jeera)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(3, 110),
    diseases: [foliar("cumin_rblight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 24, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Arid rabi spice.",
  },
  {
    id: "fenugreek",
    name: { en: "Fenugreek seed", hi: "मेथी दाना", kn: "ಮೆಂತ್ಯ", mr: "मेथी दाणे" },
    agmarknetCommodity: "Methi Seeds",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(6, 120),
    diseases: [foliar("fenugreek_rblight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 24, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rabi seed spice.",
  },
  {
    id: "methi_leaves",
    name: { en: "Fenugreek leaves", hi: "मेथी", kn: "ಮೆಂತ್ಯ ಸೊಪ್ಪು", mr: "मेथी" },
    agmarknetCommodity: "Methi(Leaves)",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(25, 40),
    diseases: [foliar("methi_leaves_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Leafy crop, very short cycle.",
  },
  {
    id: "fennel",
    name: { en: "Fennel", hi: "सौंफ", kn: "ಸೋಂಪು", mr: "बडीशेप" },
    agmarknetCommodity: "Fennel(Saunf)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(6, 150),
    diseases: [foliar("fennel_rblight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 24, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rabi seed spice.",
  },
  {
    id: "garlic",
    name: { en: "Garlic", hi: "लहसुन", kn: "ಬೆಳ್ಳುಳ್ಳಿ", mr: "लसूण" },
    agmarknetCommodity: "Garlic",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(50, 150),
    diseases: [foliar("garlic_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Cured bulbs.",
  },
  {
    id: "ajwain",
    name: { en: "Ajwain", hi: "अजवाइन", kn: "ಓಮ", mr: "ओवा" },
    agmarknetCommodity: "Ajwan",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(4, 140),
    diseases: [foliar("ajwain_rblight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 24, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rabi seed spice.",
  },
  {
    id: "nutmeg",
    name: { en: "Nutmeg", hi: "जायफल", kn: "ಜಾಯಿಕಾಯಿ", mr: "जायफळ" },
    agmarknetCommodity: "Nutmeg",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 6, qtlPerAcre: 1 }, { fromAge: 10, qtlPerAcre: 3 }, { fromAge: 15, qtlPerAcre: 4 }], 50, 0.1),
    diseases: [foliar("nutmeg_phyto", "Phytophthora rot", "ಫೈಟೊಫ್ಥೊರಾ ಕೊಳೆ", "Phytophthora spp.",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 3 },
      { ...COPPER, dryHours: 5, protectionDays: 30 }, 0.3)],
    yieldNote: "Dry nut and mace.",
  },
  {
    id: "clove",
    name: { en: "Clove", hi: "लौंग", kn: "ಲವಂಗ", mr: "लवंग" },
    agmarknetCommodity: "Cloves",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 7, qtlPerAcre: 0.5 }, { fromAge: 12, qtlPerAcre: 1.5 }, { fromAge: 18, qtlPerAcre: 2 }], 60, 0.05),
    diseases: [foliar("clove_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Dried buds.",
  },
  {
    id: "cinnamon",
    name: { en: "Cinnamon", hi: "दालचीनी", kn: "ದಾಲ್ಚಿನ್ನಿ", mr: "दालचिनी" },
    agmarknetCommodity: "Cinnamon(Dalchini)",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 3, qtlPerAcre: 1 }, { fromAge: 6, qtlPerAcre: 2.5 }, { fromAge: 10, qtlPerAcre: 3 }], 40, 0.1),
    diseases: [foliar("cinnamon_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Dried quills.",
  },
  {
    id: "tamarind",
    name: { en: "Tamarind", hi: "इमली", kn: "ಹುಣಸೆಹಣ್ಣು", mr: "चिंच" },
    agmarknetCommodity: "Tamarind Fruit",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 8, qtlPerAcre: 8 }, { fromAge: 12, qtlPerAcre: 15 }, { fromAge: 20, qtlPerAcre: 20 }], 60, 0.3),
    diseases: [foliar("tamarind_anthrac", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    yieldNote: "Mature trees, alternate bearing.",
  },
  {
    id: "guava",
    name: { en: "Guava", hi: "अमरूद", kn: "ಸೀಬೆಕಾಯಿ", mr: "पेरू" },
    agmarknetCommodity: "Guava",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 3, qtlPerAcre: 25 }, { fromAge: 5, qtlPerAcre: 50 }, { fromAge: 8, qtlPerAcre: 65 }], 30, 2),
    diseases: [foliar("guava_anthrac", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    yieldNote: "Two crops a year in many areas.",
  },
  {
    id: "orange",
    name: { en: "Orange / mandarin", hi: "संतरा", kn: "ಕಿತ್ತಳೆ", mr: "संत्रे" },
    agmarknetCommodity: "Orange",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 4, qtlPerAcre: 25 }, { fromAge: 8, qtlPerAcre: 55 }, { fromAge: 12, qtlPerAcre: 70 }], 30, 2),
    diseases: [foliar("orange_bact", "Bacterial blight", "ಬ್ಯಾಕ್ಟೀರಿಯಾ ಅಂಗಮಾರಿ", "Xanthomonas spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 34, wetDays: 2 },
      { ...COPPER, dryHours: 4, protectionDays: 15 }, 0.3)],
    yieldNote: "Citrus canker is the wet-season threat.",
  },
  {
    id: "sweet_lime",
    name: { en: "Sweet lime / mosambi", hi: "मौसंबी", kn: "ಮೂಸಂಬಿ", mr: "मोसंबी" },
    agmarknetCommodity: "Mousambi(Sweet Lime)",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 4, qtlPerAcre: 25 }, { fromAge: 8, qtlPerAcre: 55 }, { fromAge: 12, qtlPerAcre: 70 }], 30, 2),
    diseases: [foliar("sweet_lime_bact", "Bacterial blight", "ಬ್ಯಾಕ್ಟೀರಿಯಾ ಅಂಗಮಾರಿ", "Xanthomonas spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 34, wetDays: 2 },
      { ...COPPER, dryHours: 4, protectionDays: 15 }, 0.3)],
    yieldNote: "Citrus canker is the wet-season threat.",
  },
  {
    id: "lemon",
    name: { en: "Lemon", hi: "नींबू", kn: "ನಿಂಬೆಹಣ್ಣು", mr: "लिंबू" },
    agmarknetCommodity: "Lemon",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 3, qtlPerAcre: 20 }, { fromAge: 6, qtlPerAcre: 45 }, { fromAge: 10, qtlPerAcre: 55 }], 30, 1.5),
    diseases: [foliar("lemon_bact", "Bacterial blight", "ಬ್ಯಾಕ್ಟೀರಿಯಾ ಅಂಗಮಾರಿ", "Xanthomonas spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 34, wetDays: 2 },
      { ...COPPER, dryHours: 4, protectionDays: 15 }, 0.3)],
    yieldNote: "Bears through much of the year.",
  },
  {
    id: "jackfruit",
    name: { en: "Jackfruit", hi: "कटहल", kn: "ಹಲಸಿನಕಾಯಿ", mr: "फणस" },
    agmarknetCommodity: "Jack Fruit",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 6, qtlPerAcre: 30 }, { fromAge: 10, qtlPerAcre: 70 }, { fromAge: 15, qtlPerAcre: 90 }], 50, 1),
    diseases: [foliar("jackfruit_phyto", "Phytophthora rot", "ಫೈಟೊಫ್ಥೊರಾ ಕೊಳೆ", "Phytophthora spp.",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 3 },
      { ...COPPER, dryHours: 5, protectionDays: 30 }, 0.3)],
    yieldNote: "Very large fruit; yield varies hugely by tree.",
  },
  {
    id: "pineapple",
    name: { en: "Pineapple", hi: "अनानास", kn: "ಅನಾನಸ್", mr: "अननस" },
    agmarknetCommodity: "Pineapple",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(150, 450),
    diseases: [foliar("pineapple_phyto", "Phytophthora rot", "ಫೈಟೊಫ್ಥೊರಾ ಕೊಳೆ", "Phytophthora spp.",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 3 },
      { ...COPPER, dryHours: 5, protectionDays: 30 }, 0.3)],
    yieldNote: "One long cycle from sucker to fruit.",
  },
  {
    id: "muskmelon",
    name: { en: "Muskmelon", hi: "खरबूजा", kn: "ಕರಬೂಜ", mr: "खरबूज" },
    agmarknetCommodity: "Water Melon",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(90, 90),
    diseases: [foliar("muskmelon_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Summer crop on drip.",
  },
  {
    id: "apple",
    name: { en: "Apple", hi: "सेब", kn: "Apple", mr: "सफरचंद" },
    agmarknetCommodity: "Apple",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 5, qtlPerAcre: 20 }, { fromAge: 8, qtlPerAcre: 60 }, { fromAge: 12, qtlPerAcre: 90 }], 35, 2),
    diseases: [foliar("apple_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Temperate hill orchards.",
  },
  {
    id: "pear",
    name: { en: "Pear", hi: "नाशपाती", kn: "Pear", mr: "पेअर" },
    agmarknetCommodity: "Pear(Marasebu)",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 5, qtlPerAcre: 20 }, { fromAge: 8, qtlPerAcre: 55 }, { fromAge: 12, qtlPerAcre: 80 }], 35, 2),
    diseases: [foliar("pear_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Temperate hill orchards.",
  },
  {
    id: "peach",
    name: { en: "Peach", hi: "आड़ू", kn: "Peach", mr: "पीच" },
    agmarknetCommodity: "Peach",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 3, qtlPerAcre: 15 }, { fromAge: 6, qtlPerAcre: 40 }, { fromAge: 10, qtlPerAcre: 55 }], 20, 3),
    diseases: [foliar("peach_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Temperate hill orchards.",
  },
  {
    id: "plum",
    name: { en: "Plum", hi: "आलूबुखारा", kn: "Plum", mr: "आलूबुखार" },
    agmarknetCommodity: "Plum",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 3, qtlPerAcre: 12 }, { fromAge: 6, qtlPerAcre: 35 }, { fromAge: 10, qtlPerAcre: 45 }], 20, 2),
    diseases: [foliar("plum_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Temperate hill orchards.",
  },
  {
    id: "litchi",
    name: { en: "Litchi", hi: "लीची", kn: "Litchi", mr: "लिची" },
    agmarknetCommodity: "Litchi",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 5, qtlPerAcre: 10 }, { fromAge: 10, qtlPerAcre: 35 }, { fromAge: 15, qtlPerAcre: 50 }], 40, 1),
    diseases: [foliar("litchi_anthrac", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    yieldNote: "Strongly alternate bearing.",
  },
  {
    id: "ber",
    name: { en: "Ber", hi: "बेर", kn: "ಬೋರೆಹಣ್ಣು", mr: "बोर" },
    agmarknetCommodity: "Ber(Zizyphus/Borehannu)",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 3, qtlPerAcre: 20 }, { fromAge: 5, qtlPerAcre: 45 }, { fromAge: 8, qtlPerAcre: 60 }], 25, 2),
    diseases: [foliar("ber_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Arid-zone fruit.",
  },
  {
    id: "custard_apple",
    name: { en: "Custard apple", hi: "सीताफल", kn: "ಸೀತಾಫಲ", mr: "सीताफळ" },
    agmarknetCommodity: "Custard Apple (Sharifa)",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 4, qtlPerAcre: 10 }, { fromAge: 7, qtlPerAcre: 25 }, { fromAge: 10, qtlPerAcre: 32 }], 25, 1),
    diseases: [foliar("custard_apple_anthrac", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    yieldNote: "Rainfed orchards.",
  },
  {
    id: "fig",
    name: { en: "Fig", hi: "अंजीर", kn: "ಅಂಜೂರ", mr: "अंजीर" },
    agmarknetCommodity: "Fig(Anjura/Anjeer)",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 2, qtlPerAcre: 15 }, { fromAge: 4, qtlPerAcre: 40 }, { fromAge: 7, qtlPerAcre: 55 }], 20, 2),
    diseases: [foliar("fig_rust", "Rust", "ತುಕ್ಕು ರೋಗ", "Puccinia spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 28, wetDays: 3 },
      { en: "Propiconazole spray", kn: "ಪ್ರೊಪಿಕೊನಜೋಲ್ ಸಿಂಪರಣೆ", dryHours: 4, protectionDays: 21 }, 0.25)],
    yieldNote: "Bears young.",
  },
  {
    id: "amla",
    name: { en: "Amla", hi: "आंवला", kn: "ನೆಲ್ಲಿಕಾಯಿ", mr: "आवळा" },
    agmarknetCommodity: "Amla(Nelli Kai)",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 4, qtlPerAcre: 15 }, { fromAge: 8, qtlPerAcre: 50 }, { fromAge: 12, qtlPerAcre: 70 }], 40, 1),
    diseases: [foliar("amla_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Hardy, low input.",
  },
  {
    id: "strawberry",
    name: { en: "Strawberry", hi: "स्ट्रॉबेरी", kn: "Strawberry", mr: "स्ट्रॉबेरी" },
    agmarknetCommodity: "Straw Berry",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(60, 120),
    diseases: [foliar("strawberry_anthrac", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    yieldNote: "Hill and protected cultivation.",
  },
  {
    id: "mulberry",
    name: { en: "Mulberry", hi: "शहतूत", kn: "ಹಿಪ್ಪುನೇರಳೆ", mr: "तुती" },
    agmarknetCommodity: "Mulberry",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 1, qtlPerAcre: 80 }, { fromAge: 2, qtlPerAcre: 140 }, { fromAge: 3, qtlPerAcre: 180 }], 15, 10),
    diseases: [foliar("mulberry_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Leaf for sericulture, many cuts a year.",
  },
  {
    id: "radish",
    name: { en: "Radish", hi: "मूली", kn: "ಮೂಲಂಗಿ", mr: "मुळा" },
    agmarknetCommodity: "Raddish",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(60, 55),
    diseases: [foliar("radish_blight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 30, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Very short cycle.",
  },
  {
    id: "beetroot",
    name: { en: "Beetroot", hi: "चुकंदर", kn: "ಬೀಟ್‌ರೂಟ್", mr: "बीट" },
    agmarknetCommodity: "Beetroot",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(70, 90),
    diseases: [foliar("beetroot_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Roots at commercial spacing.",
  },
  {
    id: "spinach",
    name: { en: "Spinach", hi: "पालक", kn: "ಪಾಲಕ್", mr: "पालक" },
    agmarknetCommodity: "Spinach",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(40, 45),
    diseases: [foliar("spinach_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Leafy crop, multiple cuts.",
  },
  {
    id: "amaranthus",
    name: { en: "Amaranthus", hi: "चौलाई", kn: "ಹರಿವೆ ಸೊಪ್ಪು", mr: "माठ" },
    agmarknetCommodity: "Amaranthus",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(35, 40),
    diseases: [foliar("amaranthus_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Leafy crop, very short cycle.",
  },
  {
    id: "capsicum",
    name: { en: "Capsicum", hi: "शिमला मिर्च", kn: "ದೊಣ್ಣೆ ಮೆಣಸಿನಕಾಯಿ", mr: "ढोबळी मिरची" },
    agmarknetCommodity: "Capsicum",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(70, 130),
    diseases: [foliar("capsicum_anthrac", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    yieldNote: "Higher under protected cultivation.",
  },
  {
    id: "bitter_gourd",
    name: { en: "Bitter gourd", hi: "करेला", kn: "ಹಾಗಲಕಾಯಿ", mr: "कारले" },
    agmarknetCommodity: "Bitter gourd",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(60, 90),
    diseases: [foliar("bitter_gourd_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Across pickings on a trellis.",
  },
  {
    id: "bottle_gourd",
    name: { en: "Bottle gourd", hi: "लौकी", kn: "ಸೋರೆಕಾಯಿ", mr: "दुधी भोपळा" },
    agmarknetCommodity: "Bottle gourd",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(80, 90),
    diseases: [foliar("bottle_gourd_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Across pickings.",
  },
  {
    id: "ridge_gourd",
    name: { en: "Ridge gourd", hi: "तोरई", kn: "ಹೀರೆಕಾಯಿ", mr: "दोडका" },
    agmarknetCommodity: "Ridgeguard(Tori)",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(60, 90),
    diseases: [foliar("ridge_gourd_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Across pickings.",
  },
  {
    id: "snake_gourd",
    name: { en: "Snake gourd", hi: "चिचिंडा", kn: "ಪಡವಲಕಾಯಿ", mr: "पडवळ" },
    agmarknetCommodity: "Snakeguard",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(60, 90),
    diseases: [foliar("snake_gourd_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Across pickings.",
  },
  {
    id: "ash_gourd",
    name: { en: "Ash gourd", hi: "पेठा", kn: "ಬೂದುಗುಂಬಳ", mr: "कोहळा" },
    agmarknetCommodity: "Ashgourd",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(90, 110),
    diseases: [foliar("ash_gourd_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Stores well after harvest.",
  },
  {
    id: "pumpkin",
    name: { en: "Pumpkin", hi: "कद्दू", kn: "ಕುಂಬಳಕಾಯಿ", mr: "भोपळा" },
    agmarknetCommodity: "Pumpkin",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(90, 100),
    diseases: [foliar("pumpkin_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Stores well after harvest.",
  },
  {
    id: "sweet_potato",
    name: { en: "Sweet potato", hi: "शकरकंद", kn: "ಸಿಹಿ ಗೆಣಸು", mr: "रताळे" },
    agmarknetCommodity: "Sweet Potato",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(80, 120),
    diseases: [foliar("sweet_potato_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Tubers.",
  },
  {
    id: "colocasia",
    name: { en: "Colocasia", hi: "अरबी", kn: "ಕೆಸು", mr: "अळू" },
    agmarknetCommodity: "Colacasia",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(70, 180),
    diseases: [foliar("colocasia_phyto", "Phytophthora rot", "ಫೈಟೊಫ್ಥೊರಾ ಕೊಳೆ", "Phytophthora spp.",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 3 },
      { ...COPPER, dryHours: 5, protectionDays: 30 }, 0.3)],
    yieldNote: "Leaf blight follows monsoon waterlogging.",
  },
  {
    id: "elephant_yam",
    name: { en: "Elephant foot yam", hi: "सूरन", kn: "ಸುವರ್ಣಗಡ್ಡೆ", mr: "सुरण" },
    agmarknetCommodity: "Elephant Yam (Suran)",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(120, 240),
    diseases: [foliar("elephant_yam_phyto", "Phytophthora rot", "ಫೈಟೊಫ್ಥೊರಾ ಕೊಳೆ", "Phytophthora spp.",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 3 },
      { ...COPPER, dryHours: 5, protectionDays: 30 }, 0.3)],
    yieldNote: "Corms; heavy yielder.",
  },
  {
    id: "tapioca",
    name: { en: "Tapioca / cassava", hi: "कसावा", kn: "ಮರಗೆಣಸು", mr: "कसावा" },
    agmarknetCommodity: "Tapioca",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(120, 300),
    diseases: [foliar("tapioca_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Tubers, long duration.",
  },
  {
    id: "drumstick",
    name: { en: "Drumstick", hi: "सहजन", kn: "ನುಗ್ಗೆಕಾಯಿ", mr: "शेवगा" },
    agmarknetCommodity: "Drumstick",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 1, qtlPerAcre: 25 }, { fromAge: 2, qtlPerAcre: 55 }, { fromAge: 4, qtlPerAcre: 70 }], 15, 4),
    diseases: [foliar("drumstick_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Annual types bear in the first year.",
  },
  {
    id: "knol_khol",
    name: { en: "Knol khol", hi: "गांठ गोभी", kn: "ನವಿಲುಕೋಸು", mr: "नवलकोल" },
    agmarknetCommodity: "Knol Khol",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(70, 80),
    diseases: [foliar("knol_khol_bact", "Bacterial blight", "ಬ್ಯಾಕ್ಟೀರಿಯಾ ಅಂಗಮಾರಿ", "Xanthomonas spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 34, wetDays: 2 },
      { ...COPPER, dryHours: 4, protectionDays: 15 }, 0.3)],
    yieldNote: "Short-cycle cole crop.",
  },
  {
    id: "turnip",
    name: { en: "Turnip", hi: "शलजम", kn: "ಟರ್ನಿಪ್", mr: "सलगम" },
    agmarknetCommodity: "Turnip",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(70, 80),
    diseases: [foliar("turnip_blight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 30, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Cool-season root.",
  },
  {
    id: "broccoli",
    name: { en: "Broccoli", hi: "ब्रोकली", kn: "ಬ್ರೊಕೊಲಿ", mr: "ब्रोकोली" },
    agmarknetCommodity: "Broccoli",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(50, 90),
    diseases: [foliar("broccoli_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Cool-season, premium market.",
  },
  {
    id: "lettuce",
    name: { en: "Lettuce", hi: "सलाद पत्ता", kn: "ಲೆಟ್ಯೂಸ್", mr: "लेट्युस" },
    agmarknetCommodity: "Lettuce",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(50, 70),
    diseases: [foliar("lettuce_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Cool-season leafy crop.",
  },
  {
    id: "betel_leaves",
    name: { en: "Betel leaves", hi: "पान", kn: "ವೀಳ್ಯದೆಲೆ", mr: "विड्याची पाने" },
    agmarknetCommodity: "Betal Leaves",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 1, qtlPerAcre: 20 }, { fromAge: 2, qtlPerAcre: 35 }, { fromAge: 3, qtlPerAcre: 45 }], 10, 3),
    diseases: [foliar("betel_leaves_phyto", "Phytophthora rot", "ಫೈಟೊಫ್ಥೊರಾ ಕೊಳೆ", "Phytophthora spp.",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 3 },
      { ...COPPER, dryHours: 5, protectionDays: 30 }, 0.3)],
    yieldNote: "Leaf rot follows monsoon waterlogging; sold by count, so weight is approximate.",
  },
  {
    id: "lemongrass",
    name: { en: "Lemongrass", hi: "नींबू घास", kn: "ಮಜ್ಜಿಗೆ ಹುಲ್ಲು", mr: "गवती चहा" },
    agmarknetCommodity: "Lemon Grass",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 1, qtlPerAcre: 80 }, { fromAge: 2, qtlPerAcre: 140 }, { fromAge: 3, qtlPerAcre: 160 }], 8, 20),
    diseases: [foliar("lemongrass_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Herbage for oil distillation, several cuts a year.",
  },
  {
    id: "mint",
    name: { en: "Mint", hi: "पुदीना", kn: "ಪುದೀನ", mr: "पुदिना" },
    agmarknetCommodity: "Mint(Pudina)",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(60, 90),
    diseases: [foliar("mint_rust", "Rust", "ತುಕ್ಕು ರೋಗ", "Puccinia spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 28, wetDays: 3 },
      { en: "Propiconazole spray", kn: "ಪ್ರೊಪಿಕೊನಜೋಲ್ ಸಿಂಪರಣೆ", dryHours: 4, protectionDays: 21 }, 0.25)],
    yieldNote: "Several cuts per planting.",
  },
  {
    id: "aloe_vera",
    name: { en: "Aloe vera", hi: "घृतकुमारी", kn: "ಲೋಳೆಸರ", mr: "कोरफड" },
    agmarknetCommodity: "Aloe Vera",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 1, qtlPerAcre: 60 }, { fromAge: 2, qtlPerAcre: 120 }, { fromAge: 3, qtlPerAcre: 150 }], 8, 15),
    diseases: [foliar("aloe_vera_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Leaf weight; low input.",
  },
  // ---------------------------------------------------------------- newer commercial crops
  {
    id: "dragon_fruit",
    name: { en: "Dragon fruit", hi: "ड्रैगन फ्रूट", kn: "ಡ್ರ್ಯಾಗನ್ ಫ್ರೂಟ್", mr: "ड्रॅगन फ्रूट" },
    agmarknetCommodity: "Dragon Fruit",
    grades: [],
    // A cactus on a trellis: it tolerates drought far better than an orchard
    // tree and rots if kept wet, so the intervals are deliberately long.
    irrigation: { intervalDays: { drip: 5, sprinkler: 9, flood: 14, rainfed: Infinity }, rainSkipMm: 8 },
    yield: perennial([{ fromAge: 2, qtlPerAcre: 30 }, { fromAge: 3, qtlPerAcre: 60 }, { fromAge: 4, qtlPerAcre: 80 }], 18, 4),
    diseases: [foliar("dragon_anthrac", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 32, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    notes: "Stem rot follows waterlogging and overhead watering more than anything else. Keep the base dry.",
    yieldNote: "Bears from the second year, full crop from the third or fourth. Four to six flushes a year on a mature trellis.",
  },
  {
    id: "avocado",
    name: { en: "Avocado", hi: "एवोकाडो", kn: "ಬೆಣ್ಣೆ ಹಣ್ಣು", mr: "अ‍ॅव्होकॅडो" },
    agmarknetCommodity: "Avocado",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 12 },
    yield: perennial([{ fromAge: 4, qtlPerAcre: 15 }, { fromAge: 7, qtlPerAcre: 40 }, { fromAge: 10, qtlPerAcre: 60 }], 35, 1.5),
    diseases: [foliar("avocado_anthrac", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum gloeosporioides",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...COPPER, dryHours: 5, protectionDays: 21 }, 0.3)],
    notes: "Root rot from standing water kills more avocado trees than any leaf disease. Drainage first.",
    yieldNote: "Grafted trees bear from the fourth year; seedlings take longer and vary widely.",
  },
  {
    id: "passion_fruit",
    name: { en: "Passion fruit", hi: "पैशन फ्रूट", kn: "ಪ್ಯಾಶನ್ ಹಣ್ಣು", mr: "पॅशन फ्रूट" },
    agmarknetCommodity: "Passion Fruit",
    grades: [],
    irrigation: { intervalDays: { drip: 3, sprinkler: 6, flood: 10, rainfed: Infinity }, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 1, qtlPerAcre: 30 }, { fromAge: 2, qtlPerAcre: 70 }], 4, 15),
    diseases: [foliar("passion_brownspot", "Brown spot", "ಕಂದು ಚುಕ್ಕೆ ರೋಗ", "Alternaria passiflorae",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    yieldNote: "Peaks in the second and third years, then falls away — most growers replant by the fifth.",
  },
  {
    id: "kiwi",
    name: { en: "Kiwi", hi: "कीवी", kn: "ಕಿವಿ ಹಣ್ಣು", mr: "किवी" },
    agmarknetCommodity: "Kiwi",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 12 },
    yield: perennial([{ fromAge: 4, qtlPerAcre: 20 }, { fromAge: 7, qtlPerAcre: 50 }, { fromAge: 10, qtlPerAcre: 70 }], 30, 2),
    diseases: [foliar("kiwi_canker", "Bacterial canker", "ಬ್ಯಾಕ್ಟೀರಿಯಾ ಕ್ಯಾಂಕರ್", "Pseudomonas syringae pv. actinidiae",
      { months: RABI, humidityPct: 85, tempMinC: 5, tempMaxC: 20, wetDays: 2 },
      { ...COPPER, dryHours: 4, protectionDays: 21 }, 0.35)],
    yieldNote: "Temperate hill crop, and it needs a male vine nearby to set fruit at all.",
  },
  {
    id: "date_palm",
    name: { en: "Date palm", hi: "खजूर", kn: "ಖರ್ಜೂರ", mr: "खजूर" },
    agmarknetCommodity: "Dates",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 14 },
    yield: perennial([{ fromAge: 5, qtlPerAcre: 20 }, { fromAge: 8, qtlPerAcre: 50 }, { fromAge: 12, qtlPerAcre: 70 }], 50, 1),
    diseases: [foliar("date_khamedj", "Inflorescence rot", "ಹೂಗೊಂಚಲು ಕೊಳೆ", "Mauginiella scaettae",
      { months: [2, 3, 4], humidityPct: 85, tempMinC: 15, tempMaxC: 32, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 21 }, 0.3)],
    notes: "Rain at fruiting is the main threat in India, which is why the crop sits in the dry west.",
    yieldNote: "Tissue-culture palms bear from about the fifth year.",
  },
  {
    id: "saffron",
    name: { en: "Saffron", hi: "केसर", kn: "ಕೇಸರಿ", mr: "केशर" },
    agmarknetCommodity: "Saffron",
    grades: [],
    irrigation: { intervalDays: { drip: 6, sprinkler: 10, flood: 14, rainfed: Infinity }, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 1, qtlPerAcre: 0.01 }, { fromAge: 2, qtlPerAcre: 0.02 }]),
    diseases: [phytophthora({
      id: "saffron_corm_rot",
      name: { en: "Corm rot", kn: "ಗಡ್ಡೆ ಕೊಳೆ ರೋಗ" },
      pathogen: "Fusarium oxysporum",
      months: MONSOON, wetDays: 4, lossShare: 0.4,
    })],
    yieldNote: "Dried stigma only — a couple of kilograms an acre is a good year, which is why the price per quintal looks unlike any other crop.",
  },

  // ---------------------------------------------------------------- flowers
  {
    id: "marigold",
    name: { en: "Marigold", hi: "गेंदा", kn: "ಚೆಂಡು ಹೂವು", mr: "झेंडू" },
    agmarknetCommodity: "Marigold",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(50, 100),
    diseases: [foliar("marigold_blight", "Flower blight", "ಹೂ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 32, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 12 }, 0.3)],
    yieldNote: "Loose flowers across repeated pickings. Prices swing hard around festivals.",
  },
  {
    id: "rose",
    name: { en: "Rose", hi: "गुलाब", kn: "ಗುಲಾಬಿ", mr: "गुलाब" },
    agmarknetCommodity: "Rose(Loose)",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: perennial([{ fromAge: 1, qtlPerAcre: 25 }, { fromAge: 2, qtlPerAcre: 55 }, { fromAge: 3, qtlPerAcre: 65 }], 8, 6),
    diseases: [foliar("rose_blackspot", "Black spot", "ಕಪ್ಪು ಚುಕ್ಕೆ ರೋಗ", "Diplocarpon rosae",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 28, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 12 }, 0.25)],
    yieldNote: "Loose flowers by weight. Cut-stem roses under polyhouse are a different crop and a different price.",
  },
  {
    id: "jasmine",
    name: { en: "Jasmine", hi: "चमेली", kn: "ಮಲ್ಲಿಗೆ", mr: "मोगरा" },
    agmarknetCommodity: "Jasmine",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: perennial([{ fromAge: 1, qtlPerAcre: 8 }, { fromAge: 2, qtlPerAcre: 20 }, { fromAge: 4, qtlPerAcre: 26 }], 12, 2),
    diseases: [foliar("jasmine_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora jasminicola",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.2)],
    yieldNote: "Buds picked daily through the season; the summer flush carries most of the income.",
  },
  {
    id: "chrysanthemum",
    name: { en: "Chrysanthemum", hi: "गुलदाउदी", kn: "ಸೇವಂತಿಗೆ", mr: "शेवंती" },
    agmarknetCommodity: "Chrysanthemum",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(60, 120),
    diseases: [foliar("chrys_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Septoria spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 12 }, 0.25)],
    yieldNote: "Loose flowers across pickings.",
  },

];

/**
 * Fallback for a commodity with no agronomy in the registry.
 *
 * This is now reached only by an id the registry does not know — a farm saved
 * before a rename, or corrupted storage. The irrigation interval is a generic
 * default and the yield is zero rather than a guess, so the app reports what it
 * does not know instead of inventing it. Every real crop lives in CROPS.
 */
export function genericCrop(id: string, en: string, kn: string, commodity: string): CropConfig {
  return {
    id,
    // An unrecognised crop has no translations; English stands in everywhere.
    name: { en, hi: en, kn, mr: en },
    agmarknetCommodity: commodity,
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(0, 120),
    diseases: [],
  };
}
