import type { CropConfig, DiseaseRule, IrrigationMethod, PerennialYield, SeasonalYield } from "./types";

/**
 * The crop registry.
 *
 * READ THIS BEFORE TRUSTING A NUMBER HERE.
 *
 * Yield figures are conservative national ballparks, deliberately set nearer
 * the typical harvest than the headline one. Published "up to N quintals per
 * acre" figures are best-case demonstration plots; building them in would
 * inflate every farmer's revenue projection. Real yields swing by a factor of
 * three across variety, season, soil, spacing and management, so these are an
 * opening estimate the grower is expected to correct — see
 * Farm.expectedQtlPerAcre, which overrides all of this.
 *
 * Disease rules are only written where the pathogen genuinely follows the
 * "warm, wet, humid spell" shape this engine models. Powdery mildews (which
 * prefer dry weather) and insect pests (fall armyworm, fruit borer, tea
 * mosquito bug) do NOT fit it, and are deliberately absent rather than
 * shoehorned in. A crop can be economically important and still have no rule
 * here; that is honest, not incomplete.
 *
 * Everything below is pending review by an agronomist.
 */

const MONSOON = [6, 7, 8, 9, 10];
const RABI = [11, 12, 1, 2];

type Intervals = Record<IrrigationMethod, number>;

/** Water-hungry shallow-rooted vegetables. */
const VEG: Intervals = { drip: 2, sprinkler: 4, flood: 7, rainfed: Infinity };
/** Field crops and cereals. */
const FIELD: Intervals = { drip: 4, sprinkler: 7, flood: 10, rainfed: Infinity };
/** Deep-rooted orchard and plantation crops. */
const ORCHARD: Intervals = { drip: 4, sprinkler: 8, flood: 12, rainfed: Infinity };

function seasonal(qtlPerAcre: number, cycleDays: number): SeasonalYield {
  return { kind: "seasonal", qtlPerAcre, cycleDays };
}

function perennial(
  curve: { fromAge: number; qtlPerAcre: number }[],
  declineFromAge?: number,
  declinePerYear?: number,
): PerennialYield {
  return { kind: "perennial", curve, declineFromAge, declinePerYear };
}

/** Phytophthora rots share a shape: warm, soaked, humid, and Bordeaux answers them. */
function phytophthora(over: Partial<DiseaseRule> & Pick<DiseaseRule, "id" | "name">): DiseaseRule {
  return {
    pathogen: "Phytophthora spp.",
    months: MONSOON,
    humidityPct: 90,
    tempMinC: 20,
    tempMaxC: 30,
    wetDays: 3,
    treatment: {
      name: { en: "Bordeaux mixture 1%", kn: "ಬೋರ್ಡೊ ಮಿಶ್ರಣ ೧%" },
      dryHours: 6,
      protectionDays: 40,
    },
    lossShare: 0.3,
    ...over,
  };
}

/** A foliar fungus knocked back by a protectant spray on a short cycle. */
function foliar(
  id: string,
  en: string,
  kn: string,
  pathogen: string,
  band: { months: number[]; humidityPct: number; tempMinC: number; tempMaxC: number; wetDays: number },
  treatment: { en: string; kn: string; dryHours: number; protectionDays: number },
  lossShare: number,
): DiseaseRule {
  return {
    id,
    name: { en, kn },
    pathogen,
    ...band,
    treatment: {
      name: { en: treatment.en, kn: treatment.kn },
      dryHours: treatment.dryHours,
      protectionDays: treatment.protectionDays,
    },
    lossShare,
  };
}

const MANCOZEB = { en: "Mancozeb spray", kn: "ಮ್ಯಾಂಕೋಜೆಬ್ ಸಿಂಪರಣೆ" };
const COPPER = { en: "Copper oxychloride spray", kn: "ಕಾಪರ್ ಆಕ್ಸಿಕ್ಲೋರೈಡ್ ಸಿಂಪರಣೆ" };

export const CROPS: CropConfig[] = [
  // ---------------------------------------------------------------- plantation
  {
    id: "arecanut",
    name: { en: "Arecanut", kn: "ಅಡಿಕೆ" },
    agmarknetCommodity: "Arecanut(Betelnut/Supari)",
    grades: [
      { id: "rashi", label: { en: "Rashi", kn: "ರಾಶಿ" }, aliases: ["rashi", "raashi", "rashi idi"] },
      { id: "hosa_chali", label: { en: "Hosa Chali", kn: "ಹೊಸ ಚಾಲಿ" }, aliases: ["hosa chali", "hosachali", "new variety"] },
      { id: "hale_chali", label: { en: "Hale Chali", kn: "ಹಳೆ ಚಾಲಿ" }, aliases: ["hale chali", "halechali", "old variety"] },
      { id: "chippu", label: { en: "Chippu", kn: "ಚಿಪ್ಪು" }, aliases: ["chippu"] },
      { id: "bilegotu", label: { en: "Bilegotu", kn: "ಬಿಳೆಗೋಟು" }, aliases: ["bilegotu", "bile gotu"] },
      { id: "cqca", label: { en: "CQCA", kn: "ಸಿಕ್ಯುಸಿಎ" }, aliases: ["cqca", "c q c a"] },
    ],
    irrigation: { intervalDays: { drip: 3, sprinkler: 6, flood: 8, rainfed: Infinity }, rainSkipMm: 10 },
    yield: perennial([
      { fromAge: 5, qtlPerAcre: 2.7 },
      { fromAge: 6, qtlPerAcre: 4.5 },
      { fromAge: 7, qtlPerAcre: 6.8 },
      { fromAge: 8, qtlPerAcre: 9 },
    ], 40, 0.3),
    diseases: [phytophthora({ id: "koleroga", name: { en: "Koleroga (fruit rot)", kn: "ಕೊಳೆರೋಗ" }, pathogen: "Phytophthora meadii" })],
    notes: "Yellow Leaf Disease has no cure. Photograph yellowing fronds to build a per-block record.",
    yieldNote: "Chali basis, well-managed garden. Coastal gardens on good soil exceed this; diseased blocks fall far below.",
  },
  {
    id: "coconut",
    name: { en: "Coconut", kn: "ತೆಂಗು" },
    agmarknetCommodity: "Coconut",
    grades: [],
    irrigation: { intervalDays: { drip: 4, sprinkler: 7, flood: 10, rainfed: Infinity }, rainSkipMm: 12 },
    yield: perennial([
      { fromAge: 6, qtlPerAcre: 3 },
      { fromAge: 8, qtlPerAcre: 6 },
      { fromAge: 10, qtlPerAcre: 8 },
    ], 50, 0.2),
    diseases: [phytophthora({
      id: "bud_rot",
      name: { en: "Bud rot", kn: "ಸುಳಿ ಕೊಳೆ" },
      pathogen: "Phytophthora palmivora",
      treatment: { name: { en: "Bordeaux mixture 1% to the crown", kn: "ಸುಳಿಗೆ ಬೋರ್ಡೊ ಮಿಶ್ರಣ ೧%" }, dryHours: 6, protectionDays: 45 },
      lossShare: 0.25,
    })],
    yieldNote: "Agmarknet quotes coconut by weight, so this is a rough conversion from nut counts.",
  },
  {
    id: "copra",
    name: { en: "Copra", kn: "ಕೊಬ್ಬರಿ" },
    agmarknetCommodity: "Copra",
    grades: [],
    irrigation: { intervalDays: { drip: 4, sprinkler: 7, flood: 10, rainfed: Infinity }, rainSkipMm: 12 },
    yield: perennial([{ fromAge: 6, qtlPerAcre: 1.5 }, { fromAge: 8, qtlPerAcre: 3 }, { fromAge: 10, qtlPerAcre: 4 }], 50, 0.1),
    diseases: [phytophthora({ id: "copra_bud_rot", name: { en: "Bud rot", kn: "ಸುಳಿ ಕೊಳೆ" }, pathogen: "Phytophthora palmivora", lossShare: 0.25 })],
    yieldNote: "Dried kernel, roughly half the fresh nut weight of the same garden.",
  },
  {
    id: "black_pepper",
    name: { en: "Black pepper", kn: "ಕರಿಮೆಣಸು" },
    agmarknetCommodity: "Black pepper",
    grades: [],
    irrigation: { intervalDays: { drip: 4, sprinkler: 7, flood: 10, rainfed: Infinity }, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 3, qtlPerAcre: 0.8 }, { fromAge: 5, qtlPerAcre: 2 }, { fromAge: 7, qtlPerAcre: 2.8 }], 25, 0.1),
    diseases: [phytophthora({ id: "quick_wilt", name: { en: "Quick wilt (foot rot)", kn: "ಸೊರಗು ರೋಗ" }, pathogen: "Phytophthora capsici", wetDays: 2, lossShare: 0.4 })],
    yieldNote: "Dry pepper from vines on standards. Yield depends heavily on the standard tree and shade.",
  },
  {
    id: "cocoa",
    name: { en: "Cocoa", kn: "ಕೋಕೋ" },
    agmarknetCommodity: "Cocoa",
    grades: [],
    irrigation: { intervalDays: { drip: 4, sprinkler: 7, flood: 9, rainfed: Infinity }, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 3, qtlPerAcre: 1.2 }, { fromAge: 5, qtlPerAcre: 3 }, { fromAge: 7, qtlPerAcre: 4 }]),
    diseases: [phytophthora({
      id: "black_pod",
      name: { en: "Black pod", kn: "ಕಪ್ಪು ಕಾಯಿ ಕೊಳೆ" },
      pathogen: "Phytophthora palmivora",
      treatment: { name: { en: "Bordeaux mixture 1%", kn: "ಬೋರ್ಡೊ ಮಿಶ್ರಣ ೧%" }, dryHours: 5, protectionDays: 30 },
    })],
    yieldNote: "Dry bean, usually intercropped under arecanut or coconut.",
  },
  {
    id: "cardamom",
    name: { en: "Cardamom", kn: "ಏಲಕ್ಕಿ" },
    agmarknetCommodity: "Cardamoms",
    grades: [],
    irrigation: { intervalDays: { drip: 3, sprinkler: 6, flood: 9, rainfed: Infinity }, rainSkipMm: 12 },
    yield: perennial([{ fromAge: 2, qtlPerAcre: 0.2 }, { fromAge: 3, qtlPerAcre: 0.5 }, { fromAge: 5, qtlPerAcre: 0.7 }]),
    diseases: [phytophthora({ id: "capsule_rot", name: { en: "Capsule rot (azhukal)", kn: "ಕಾಯಿ ಕೊಳೆ" }, lossShare: 0.35 })],
    yieldNote: "Cured capsules. A very wide range in practice — shade-grown estates differ sharply from open plots.",
  },
  {
    id: "coffee",
    name: { en: "Coffee", kn: "ಕಾಫಿ" },
    agmarknetCommodity: "Coffee",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 12 },
    yield: perennial([{ fromAge: 4, qtlPerAcre: 3 }, { fromAge: 6, qtlPerAcre: 6 }, { fromAge: 8, qtlPerAcre: 7 }], 30, 0.2),
    diseases: [foliar("leaf_rust", "Coffee leaf rust", "ಕಾಫಿ ತುಕ್ಕು ರೋಗ", "Hemileia vastatrix",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 28, wetDays: 3 },
      { ...COPPER, dryHours: 5, protectionDays: 45 }, 0.25)],
    yieldNote: "Clean coffee. Arabica typically yields below robusta on the same acreage.",
  },
  {
    id: "cashew",
    name: { en: "Cashew", kn: "ಗೋಡಂಬಿ" },
    agmarknetCommodity: "Cashewnuts",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 12 },
    yield: perennial([{ fromAge: 4, qtlPerAcre: 2 }, { fromAge: 6, qtlPerAcre: 4 }, { fromAge: 8, qtlPerAcre: 5 }], 25, 0.15),
    diseases: [foliar("cashew_anthracnose", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum gloeosporioides", { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 3 }, { ...COPPER, dryHours: 5, protectionDays: 21 }, 0.25)],
    notes: "The main cashew problem is tea mosquito bug, an insect pest. This app only models weather-driven diseases, so it will not warn you about it.",
    yieldNote: "Raw nut. Grafted varieties outyield seedling trees substantially.",
  },

  // ---------------------------------------------------------------- fruit
  {
    id: "grapes",
    name: { en: "Grapes", kn: "ದ್ರಾಕ್ಷಿ" },
    agmarknetCommodity: "Grapes",
    grades: [],
    irrigation: { intervalDays: { drip: 2, sprinkler: 5, flood: 9, rainfed: Infinity }, rainSkipMm: 8 },
    yield: perennial([{ fromAge: 3, qtlPerAcre: 40 }, { fromAge: 4, qtlPerAcre: 80 }, { fromAge: 6, qtlPerAcre: 100 }], 18, 4),
    diseases: [foliar("downy_mildew", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Plasmopara viticola",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 27, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 10 }, 0.45)],
    notes: "Powdery mildew is the other major grape disease, but it spreads in dry weather, so this app's wet-spell rules will not catch it.",
    yieldNote: "Table grapes on a well-managed trellis. Raisin varieties and young vines yield considerably less.",
  },
  {
    id: "mango",
    name: { en: "Mango", kn: "ಮಾವು" },
    agmarknetCommodity: "Mango",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 12 },
    yield: perennial([{ fromAge: 5, qtlPerAcre: 8 }, { fromAge: 8, qtlPerAcre: 20 }, { fromAge: 12, qtlPerAcre: 30 }], 40, 0.5),
    diseases: [foliar("anthracnose", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum gloeosporioides",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 3 },
      { ...COPPER, dryHours: 5, protectionDays: 21 }, 0.3)],
    notes: "Mango alternates: a heavy year is usually followed by a light one, which this estimate does not model.",
    yieldNote: "Mature orchard average across on and off years.",
  },
  {
    id: "pomegranate",
    name: { en: "Pomegranate", kn: "ದಾಳಿಂಬೆ" },
    agmarknetCommodity: "Pomegranate",
    grades: [],
    irrigation: { intervalDays: { drip: 3, sprinkler: 6, flood: 10, rainfed: Infinity }, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 3, qtlPerAcre: 20 }, { fromAge: 5, qtlPerAcre: 45 }, { fromAge: 7, qtlPerAcre: 55 }], 15, 3),
    diseases: [foliar("bacterial_blight", "Bacterial blight (telya)", "ತೆಲ್ಯಾ ರೋಗ", "Xanthomonas axonopodis",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 32, wetDays: 2 },
      { en: "Copper oxychloride + streptocycline", kn: "ಕಾಪರ್ ಆಕ್ಸಿಕ್ಲೋರೈಡ್ + ಸ್ಟ್ರೆಪ್ಟೊಸೈಕ್ಲಿನ್", dryHours: 4, protectionDays: 14 }, 0.5)],
    yieldNote: "Telya can take an entire orchard, so realised yields vary far more than this figure suggests.",
  },
  {
    id: "banana",
    name: { en: "Banana", kn: "ಬಾಳೆ" },
    agmarknetCommodity: "Banana",
    grades: [],
    irrigation: { intervalDays: { drip: 2, sprinkler: 4, flood: 7, rainfed: Infinity }, rainSkipMm: 10 },
    yield: seasonal(120, 330),
    diseases: [foliar("sigatoka", "Sigatoka leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Mycosphaerella spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 32, wetDays: 3 },
      { en: "Propiconazole spray", kn: "ಪ್ರೊಪಿಕೊನಜೋಲ್ ಸಿಂಪರಣೆ", dryHours: 5, protectionDays: 30 }, 0.25)],
    yieldNote: "One full crop cycle at commercial spacing.",
  },
  {
    id: "sapota",
    name: { en: "Sapota", kn: "ಸಪೋಟ" },
    agmarknetCommodity: "Sapota",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 12 },
    yield: perennial([{ fromAge: 5, qtlPerAcre: 20 }, { fromAge: 8, qtlPerAcre: 45 }, { fromAge: 12, qtlPerAcre: 60 }], 40, 0.6),
    diseases: [foliar("sapota_leaf_spot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Phaeophleospora indica", { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 32, wetDays: 3 }, { ...MANCOZEB, dryHours: 4, protectionDays: 21 }, 0.2)],
    yieldNote: "Mature orchard. Bears over a long season rather than one harvest.",
  },
  {
    id: "papaya",
    name: { en: "Papaya", kn: "ಪಪ್ಪಾಯಿ" },
    agmarknetCommodity: "Papaya",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 1, qtlPerAcre: 150 }, { fromAge: 2, qtlPerAcre: 250 }], 3, 80),
    diseases: [foliar("papaya_anthracnose", "Anthracnose (fruit rot)", "ಹಣ್ಣು ಕೊಳೆ ರೋಗ", "Colletotrichum gloeosporioides", { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 2 }, { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    notes: "Papaya ring spot is a virus spread by aphids, not weather, so no spray window is offered for it.",
    yieldNote: "Heaviest in the second year, then falls away sharply — most growers replant after three.",
  },
  {
    id: "watermelon",
    name: { en: "Watermelon", kn: "ಕಲ್ಲಂಗಡಿ" },
    agmarknetCommodity: "Water Melon",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(110, 90),
    diseases: [foliar("melon_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora cubensis", { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 }, { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Summer crop on drip with mulch. Open flood-irrigated plots yield well below this.",
  },

  // ---------------------------------------------------------------- vegetables
  {
    id: "tomato",
    name: { en: "Tomato", kn: "ಟೊಮೇಟೊ" },
    agmarknetCommodity: "Tomato",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(90, 100),
    diseases: [foliar("late_blight", "Late blight", "ಅಂಗಮಾರಿ ರೋಗ", "Phytophthora infestans",
      { months: [6, 7, 8, 9, 10, 11, 12], humidityPct: 88, tempMinC: 12, tempMaxC: 25, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 10 }, 0.5)],
    yieldNote: "Hybrid on stakes. Open-pollinated varieties give roughly half this.",
  },
  {
    id: "onion",
    name: { en: "Onion", kn: "ಈರುಳ್ಳಿ" },
    agmarknetCommodity: "Onion",
    grades: [],
    irrigation: { intervalDays: { drip: 3, sprinkler: 6, flood: 10, rainfed: Infinity }, rainSkipMm: 8 },
    yield: seasonal(100, 120),
    diseases: [foliar("purple_blotch", "Purple blotch", "ನೇರಳೆ ಮಚ್ಚೆ ರೋಗ", "Alternaria porri",
      { months: MONSOON, humidityPct: 80, tempMinC: 21, tempMaxC: 32, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 12 }, 0.35)],
    notes: "Onion needs a sticker with the spray — the leaves shed plain water.",
    yieldNote: "Rabi crop. Kharif onion typically yields a fifth to a third less.",
  },
  {
    id: "potato",
    name: { en: "Potato", kn: "ಆಲೂಗಡ್ಡೆ" },
    agmarknetCommodity: "Potato",
    grades: [],
    irrigation: { intervalDays: { drip: 3, sprinkler: 5, flood: 8, rainfed: Infinity }, rainSkipMm: 8 },
    yield: seasonal(80, 100),
    diseases: [foliar("potato_late_blight", "Late blight", "ಅಂಗಮಾರಿ ರೋಗ", "Phytophthora infestans",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 22, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 10 }, 0.5)],
    yieldNote: "Cool-season crop on good seed. Late blight in a wet December can halve it.",
  },
  {
    id: "green_chilli",
    name: { en: "Green chilli", kn: "ಹಸಿಮೆಣಸಿನಕಾಯಿ" },
    agmarknetCommodity: "Green Chilli",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(60, 150),
    diseases: [foliar("chilli_anthracnose", "Fruit rot (anthracnose)", "ಹಣ್ಣು ಕೊಳೆ ರೋಗ", "Colletotrichum capsici",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 12 }, 0.4)],
    notes: "Leaf curl from thrips and mites causes more loss than any fungus in many seasons, and is not modelled here.",
    yieldNote: "Green harvest across multiple pickings. Dry chilli is roughly a quarter of this weight.",
  },
  {
    id: "brinjal",
    name: { en: "Brinjal", kn: "ಬದನೆಕಾಯಿ" },
    agmarknetCommodity: "Brinjal",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(100, 150),
    diseases: [foliar("phomopsis", "Phomopsis blight (fruit rot)", "ಹಣ್ಣು ಕೊಳೆ ರೋಗ", "Phomopsis vexans", { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 32, wetDays: 2 }, { ...MANCOZEB, dryHours: 4, protectionDays: 12 }, 0.3)],
    notes: "Shoot and fruit borer is the main brinjal problem. It is an insect, so this app offers no spray window for it.",
    yieldNote: "Across the full picking season, not a single harvest.",
  },
  {
    id: "bhindi",
    name: { en: "Okra", kn: "ಬೆಂಡೆಕಾಯಿ" },
    agmarknetCommodity: "Bhindi(Ladies Finger)",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(50, 120),
    diseases: [foliar("okra_leaf_spot", "Cercospora leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora abelmoschi", { months: MONSOON, humidityPct: 85, tempMinC: 20, tempMaxC: 32, wetDays: 3 }, { ...MANCOZEB, dryHours: 4, protectionDays: 12 }, 0.2)],
    notes: "Yellow vein mosaic is a whitefly-borne virus; controlling the whitefly matters more than any fungicide.",
    yieldNote: "Total across pickings.",
  },
  {
    id: "cabbage",
    name: { en: "Cabbage", kn: "ಎಲೆಕೋಸು" },
    agmarknetCommodity: "Cabbage",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(100, 90),
    diseases: [foliar("black_rot", "Black rot", "ಕಪ್ಪು ಕೊಳೆ ರೋಗ", "Xanthomonas campestris", { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 32, wetDays: 2 }, { ...COPPER, dryHours: 4, protectionDays: 12 }, 0.35)],
    yieldNote: "Heads at commercial spacing.",
  },
  {
    id: "cauliflower",
    name: { en: "Cauliflower", kn: "ಹೂಕೋಸು" },
    agmarknetCommodity: "Cauliflower",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(80, 90),
    diseases: [foliar("crucifer_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Peronospora parasitica", { months: RABI, humidityPct: 88, tempMinC: 8, tempMaxC: 22, wetDays: 2 }, { ...MANCOZEB, dryHours: 4, protectionDays: 12 }, 0.3)],
    yieldNote: "Curd weight. Very sensitive to sowing date — a late crop can fail to head at all.",
  },
  {
    id: "carrot",
    name: { en: "Carrot", kn: "ಕ್ಯಾರೆಟ್" },
    agmarknetCommodity: "Carrot",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(70, 100),
    diseases: [foliar("carrot_blight", "Alternaria leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria dauci", { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 30, wetDays: 3 }, { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Needs deep loose soil; heavy soils give forked roots and lower marketable yield.",
  },
  {
    id: "cucumber",
    name: { en: "Cucumber", kn: "ಸೌತೆಕಾಯಿ" },
    agmarknetCommodity: "Cucumbar(Kheera)",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(70, 70),
    diseases: [foliar("cucurbit_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora cubensis",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.4)],
    yieldNote: "Across pickings on a short cycle.",
  },
  {
    id: "beans",
    name: { en: "Beans", kn: "ಹುರುಳಿಕಾಯಿ" },
    agmarknetCommodity: "Beans",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 8 },
    yield: seasonal(35, 90),
    diseases: [foliar("bean_anthracnose", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum lindemuthianum", { months: MONSOON, humidityPct: 88, tempMinC: 15, tempMaxC: 26, wetDays: 2 }, { ...MANCOZEB, dryHours: 4, protectionDays: 12 }, 0.3)],
    yieldNote: "Green pods across pickings. Pole types outyield bush types.",
  },

  // ---------------------------------------------------------------- field crops
  {
    id: "paddy",
    name: { en: "Paddy", kn: "ಭತ್ತ" },
    agmarknetCommodity: "Paddy(Dhan)(Common)",
    grades: [],
    irrigation: { intervalDays: { drip: 5, sprinkler: 5, flood: 4, rainfed: Infinity }, rainSkipMm: 15 },
    yield: seasonal(20, 125),
    diseases: [foliar("blast", "Rice blast", "ಬೆಂಕಿ ರೋಗ", "Pyricularia oryzae",
      { months: [7, 8, 9, 10, 11], humidityPct: 90, tempMinC: 20, tempMaxC: 28, wetDays: 2 },
      { en: "Tricyclazole spray", kn: "ಟ್ರೈಸೈಕ್ಲಜೋಲ್ ಸಿಂಪರಣೆ", dryHours: 4, protectionDays: 21 }, 0.3)],
    yieldNote: "Irrigated crop. Rainfed paddy commonly yields half this.",
  },
  {
    id: "ragi",
    name: { en: "Ragi", kn: "ರಾಗಿ" },
    agmarknetCommodity: "Ragi (Finger Millet)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 12 },
    yield: seasonal(12, 110),
    diseases: [foliar("ragi_blast", "Finger blast", "ಬೆಂಕಿ ರೋಗ", "Pyricularia grisea",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { en: "Carbendazim spray", kn: "ಕಾರ್ಬೆಂಡಜಿಮ್ ಸಿಂಪರಣೆ", dryHours: 4, protectionDays: 20 }, 0.3)],
    yieldNote: "Mostly grown rainfed in Karnataka; irrigated plots do better.",
  },
  {
    id: "maize",
    name: { en: "Maize", kn: "ಮೆಕ್ಕೆಜೋಳ" },
    agmarknetCommodity: "Maize",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 12 },
    yield: seasonal(25, 100),
    diseases: [foliar("turcicum", "Turcicum leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Exserohilum turcicum",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 28, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    notes: "Fall armyworm is the bigger threat in most seasons and is an insect, so no spray window is given for it.",
    yieldNote: "Hybrid grain at 14% moisture.",
  },
  {
    id: "jowar",
    name: { en: "Jowar", kn: "ಜೋಳ" },
    agmarknetCommodity: "Jowar(Sorghum)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 12 },
    yield: seasonal(12, 110),
    diseases: [foliar("grain_mould", "Grain mould", "ಕಾಳು ಬೂಷ್ಟು", "Fusarium spp.", { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 3 }, { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.3)],
    yieldNote: "Grain only. Rabi jowar on residual moisture yields less than the kharif crop.",
  },
  {
    id: "wheat",
    name: { en: "Wheat", kn: "ಗೋಧಿ" },
    agmarknetCommodity: "Wheat",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 12 },
    yield: seasonal(18, 120),
    diseases: [foliar("yellow_rust", "Yellow rust", "ಹಳದಿ ತುಕ್ಕು", "Puccinia striiformis",
      { months: RABI, humidityPct: 80, tempMinC: 5, tempMaxC: 18, wetDays: 2 },
      { en: "Propiconazole spray", kn: "ಪ್ರೊಪಿಕೊನಜೋಲ್ ಸಿಂಪರಣೆ", dryHours: 4, protectionDays: 21 }, 0.3)],
    yieldNote: "Irrigated crop with full fertiliser.",
  },
  {
    id: "groundnut",
    name: { en: "Groundnut", kn: "ಕಡಲೆಕಾಯಿ" },
    agmarknetCommodity: "Groundnut",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(10, 110),
    diseases: [foliar("late_leaf_spot", "Late leaf spot (tikka)", "ಟಿಕ್ಕಾ ರೋಗ", "Phaeoisariopsis personata",
      { months: MONSOON, humidityPct: 85, tempMinC: 20, tempMaxC: 30, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.3)],
    yieldNote: "Dry pods. Published figures of 20-25 qtl/acre are demonstration plots, not field averages.",
  },
  {
    id: "sunflower",
    name: { en: "Sunflower", kn: "ಸೂರ್ಯಕಾಂತಿ" },
    agmarknetCommodity: "Sunflower",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(6, 100),
    diseases: [foliar("sunflower_blight", "Alternaria leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria helianthi", { months: MONSOON, humidityPct: 85, tempMinC: 20, tempMaxC: 30, wetDays: 3 }, { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Seed. Birds take a meaningful share in small plots.",
  },
  {
    id: "soyabean",
    name: { en: "Soyabean", kn: "ಸೋಯಾಬೀನ್" },
    agmarknetCommodity: "Soyabean",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 12 },
    yield: seasonal(10, 100),
    diseases: [foliar("soy_rust", "Soybean rust", "ತುಕ್ಕು ರೋಗ", "Phakopsora pachyrhizi", { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 28, wetDays: 3 }, { en: "Propiconazole spray", kn: "ಪ್ರೊಪಿಕೊನಜೋಲ್ ಸಿಂಪರಣೆ", dryHours: 4, protectionDays: 21 }, 0.3)],
    yieldNote: "Grain, largely rainfed.",
  },
  {
    id: "tur",
    name: { en: "Tur / red gram", kn: "ತೊಗರಿ" },
    agmarknetCommodity: "Arhar (Tur/Red Gram)(Whole)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 12 },
    yield: seasonal(6, 180),
    diseases: [phytophthora({ id: "tur_blight", name: { en: "Phytophthora blight", kn: "ಫೈಟೊಫ್ಥೊರಾ ಅಂಗಮಾರಿ" }, wetDays: 3, treatment: { name: { ...MANCOZEB }, dryHours: 4, protectionDays: 21 }, lossShare: 0.25 })],
    notes: "Pod borer decides most tur harvests, and it is an insect pest this app does not model.",
    yieldNote: "Long-duration crop, usually rainfed.",
  },
  {
    id: "bengal_gram",
    name: { en: "Bengal gram", kn: "ಕಡಲೆ" },
    agmarknetCommodity: "Bengal Gram(Gram)(Whole)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 12 },
    yield: seasonal(8, 110),
    diseases: [foliar("ascochyta", "Ascochyta blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Ascochyta rabiei", { months: RABI, humidityPct: 85, tempMinC: 10, tempMaxC: 25, wetDays: 2 }, { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.3)],
    yieldNote: "Rabi crop, often on residual moisture.",
  },
  {
    id: "green_gram",
    name: { en: "Green gram", kn: "ಹೆಸರುಕಾಳು" },
    agmarknetCommodity: "Green Gram (Moong)(Whole)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(4, 70),
    diseases: [foliar("moong_leaf_spot", "Cercospora leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora canescens", { months: MONSOON, humidityPct: 85, tempMinC: 20, tempMaxC: 32, wetDays: 3 }, { ...MANCOZEB, dryHours: 4, protectionDays: 12 }, 0.25)],
    yieldNote: "Short-duration pulse, commonly grown as a catch crop.",
  },
  {
    id: "cotton",
    name: { en: "Cotton", kn: "ಹತ್ತಿ" },
    agmarknetCommodity: "Cotton",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 12 },
    yield: seasonal(10, 180),
    diseases: [foliar("cotton_blight", "Bacterial blight", "ಬ್ಯಾಕ್ಟೀರಿಯಾ ಅಂಗಮಾರಿ", "Xanthomonas citri pv. malvacearum", { months: MONSOON, humidityPct: 88, tempMinC: 22, tempMaxC: 34, wetDays: 2 }, { ...COPPER, dryHours: 4, protectionDays: 15 }, 0.25)],
    notes: "Pink bollworm governs cotton returns and is an insect pest, so no spray window is offered.",
    yieldNote: "Seed cotton (kapas), not lint.",
  },
  {
    id: "sugarcane",
    name: { en: "Sugarcane", kn: "ಕಬ್ಬು" },
    agmarknetCommodity: "Sugarcane",
    grades: [],
    irrigation: { intervalDays: { drip: 4, sprinkler: 8, flood: 12, rainfed: Infinity }, rainSkipMm: 15 },
    yield: seasonal(350, 365),
    diseases: [foliar("cane_rust", "Cane rust", "ಕಬ್ಬು ತುಕ್ಕು", "Puccinia melanocephala", { months: MONSOON, humidityPct: 85, tempMinC: 20, tempMaxC: 30, wetDays: 3 }, { en: "Propiconazole spray", kn: "ಪ್ರೊಪಿಕೊನಜೋಲ್ ಸಿಂಪರಣೆ", dryHours: 5, protectionDays: 30 }, 0.2)],
    notes: "Red rot is managed by choosing resistant setts, not by spraying, so no spray window applies.",
    yieldNote: "Cane weight over a full twelve-month crop. Ratoon crops yield less than plant cane.",
  },
  {
    id: "turmeric",
    name: { en: "Turmeric", kn: "ಅರಿಶಿನ" },
    agmarknetCommodity: "Turmeric",
    grades: [],
    irrigation: { intervalDays: { drip: 3, sprinkler: 6, flood: 9, rainfed: Infinity }, rainSkipMm: 12 },
    yield: seasonal(80, 240),
    diseases: [foliar("rhizome_rot", "Rhizome rot", "ಗಡ್ಡೆ ಕೊಳೆ ರೋಗ", "Pythium spp.",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 32, wetDays: 4 },
      { en: "Metalaxyl + mancozeb drench", kn: "ಮೆಟಲಾಕ್ಸಿಲ್ + ಮ್ಯಾಂಕೋಜೆಬ್ ಡ್ರೆಂಚ್", dryHours: 3, protectionDays: 30 }, 0.35)],
    yieldNote: "Fresh rhizome. Dry turmeric is roughly a fifth of this weight.",
  },
  {
    id: "ginger",
    name: { en: "Ginger", kn: "ಶುಂಠಿ" },
    agmarknetCommodity: "Ginger(Green)",
    grades: [],
    irrigation: { intervalDays: { drip: 3, sprinkler: 6, flood: 9, rainfed: Infinity }, rainSkipMm: 12 },
    yield: seasonal(70, 240),
    diseases: [foliar("soft_rot", "Soft rot", "ಮೃದು ಕೊಳೆ ರೋಗ", "Pythium aphanidermatum",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 32, wetDays: 4 },
      { en: "Metalaxyl + mancozeb drench", kn: "ಮೆಟಲಾಕ್ಸಿಲ್ + ಮ್ಯಾಂಕೋಜೆಬ್ ಡ್ರೆಂಚ್", dryHours: 3, protectionDays: 30 }, 0.4)],
    notes: "Soft rot follows waterlogging. Drainage matters more than any drench.",
    yieldNote: "Fresh rhizome.",
  },

  // ---------------------------------------------------------------- wider India
  {
    id: "bajra",
    name: { en: "Bajra", kn: "ಸಜ್ಜೆ" },
    agmarknetCommodity: "Bajra(Pearl Millet/Cumbu)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(10, 90),
    diseases: [foliar("bajra_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Rainfed kharif grain.",
  },
  {
    id: "barley",
    name: { en: "Barley", kn: "ಬಾರ್ಲಿ" },
    agmarknetCommodity: "Barley (Jau)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(15, 120),
    diseases: [foliar("barley_rrust", "Rust", "ತುಕ್ಕು ರೋಗ", "Puccinia spp.",
      { months: RABI, humidityPct: 80, tempMinC: 5, tempMaxC: 20, wetDays: 2 },
      { en: "Propiconazole spray", kn: "ಪ್ರೊಪಿಕೊನಜೋಲ್ ಸಿಂಪರಣೆ", dryHours: 4, protectionDays: 21 }, 0.25)],
    yieldNote: "Irrigated rabi grain.",
  },
  {
    id: "foxtail_millet",
    name: { en: "Foxtail millet", kn: "ನವಣೆ" },
    agmarknetCommodity: "Foxtail Millet(Navane)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(8, 80),
    diseases: [foliar("foxtail_millet_blight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 30, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rainfed minor millet.",
  },
  {
    id: "kodo_millet",
    name: { en: "Kodo millet", kn: "ಹಾರಕ" },
    agmarknetCommodity: "Kodo Millet(Varagu)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(7, 110),
    diseases: [foliar("kodo_millet_blight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 30, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rainfed minor millet.",
  },
  {
    id: "little_millet",
    name: { en: "Little millet", kn: "ಸಾಮೆ" },
    agmarknetCommodity: "Little Millet (Kutki)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(6, 90),
    diseases: [foliar("little_millet_blight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 30, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rainfed minor millet.",
  },
  {
    id: "oats",
    name: { en: "Oats", kn: "ಓಟ್ಸ್" },
    agmarknetCommodity: "Oat",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(12, 110),
    diseases: [foliar("oats_rrust", "Rust", "ತುಕ್ಕು ರೋಗ", "Puccinia spp.",
      { months: RABI, humidityPct: 80, tempMinC: 5, tempMaxC: 20, wetDays: 2 },
      { en: "Propiconazole spray", kn: "ಪ್ರೊಪಿಕೊನಜೋಲ್ ಸಿಂಪರಣೆ", dryHours: 4, protectionDays: 21 }, 0.25)],
    yieldNote: "Mostly grown as fodder.",
  },
  {
    id: "urad",
    name: { en: "Urad / black gram", kn: "ಉದ್ದು" },
    agmarknetCommodity: "Black Gram (Urd Beans)(Whole)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(4, 80),
    diseases: [foliar("urad_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Short-duration pulse.",
  },
  {
    id: "lentil",
    name: { en: "Lentil / masoor", kn: "ಮಸೂರ್" },
    agmarknetCommodity: "Lentil (Masur)(Whole)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(6, 110),
    diseases: [foliar("lentil_rblight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 24, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rabi pulse on residual moisture.",
  },
  {
    id: "horse_gram",
    name: { en: "Horse gram", kn: "ಹುರುಳಿ" },
    agmarknetCommodity: "Horse Gram",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(4, 100),
    diseases: [foliar("horse_gram_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Hardy rainfed pulse.",
  },
  {
    id: "cowpea",
    name: { en: "Cowpea", kn: "ಅಲಸಂದೆ" },
    agmarknetCommodity: "Cowpea(Veg)",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(30, 75),
    diseases: [foliar("cowpea_anthrac", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    yieldNote: "Green pods across pickings.",
  },
  {
    id: "field_pea",
    name: { en: "Field pea", kn: "ಬಟಾಣಿ" },
    agmarknetCommodity: "Peas(Dry)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(8, 110),
    diseases: [foliar("field_pea_rblight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 24, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rabi pulse.",
  },
  {
    id: "moth_bean",
    name: { en: "Moth bean", kn: "ಮಟಕಿ" },
    agmarknetCommodity: "Math",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(3, 75),
    diseases: [foliar("moth_bean_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Arid-zone pulse.",
  },
  {
    id: "rajma",
    name: { en: "Rajma", kn: "ರಾಜ್ಮಾ" },
    agmarknetCommodity: "Rajmash",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(8, 120),
    diseases: [foliar("rajma_anthrac", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    yieldNote: "Hill and rabi crop.",
  },
  {
    id: "green_peas",
    name: { en: "Green peas", kn: "ಹಸಿ ಬಟಾಣಿ" },
    agmarknetCommodity: "Peas Wet",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(40, 100),
    diseases: [foliar("green_peas_rblight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 24, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Green pods, single season.",
  },
  {
    id: "cluster_beans",
    name: { en: "Cluster beans", kn: "ಗೋರಿಕಾಯಿ" },
    agmarknetCommodity: "Cluster beans",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(30, 90),
    diseases: [foliar("cluster_beans_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Green pods across pickings.",
  },
  {
    id: "mustard",
    name: { en: "Mustard", kn: "ಸಾಸಿವೆ" },
    agmarknetCommodity: "Mustard",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(7, 120),
    diseases: [foliar("mustard_rblight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 24, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rabi oilseed.",
  },
  {
    id: "sesamum",
    name: { en: "Sesamum", kn: "ಎಳ್ಳು" },
    agmarknetCommodity: "Sesamum(Sesame,Gingelly,Til)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(3, 90),
    diseases: [foliar("sesamum_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Largely rainfed.",
  },
  {
    id: "castor",
    name: { en: "Castor", kn: "ಹರಳು" },
    agmarknetCommodity: "Castor Seed",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(8, 150),
    diseases: [foliar("castor_blight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 30, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Long-duration rainfed oilseed.",
  },
  {
    id: "safflower",
    name: { en: "Safflower", kn: "ಕುಸುಬೆ" },
    agmarknetCommodity: "Safflower",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(5, 130),
    diseases: [foliar("safflower_rblight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 24, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rabi on residual moisture.",
  },
  {
    id: "niger",
    name: { en: "Niger", kn: "ಗುರೆಳ್ಳು" },
    agmarknetCommodity: "Niger Seed (Ramtil)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(2, 100),
    diseases: [foliar("niger_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Tribal and rainfed tracts.",
  },
  {
    id: "linseed",
    name: { en: "Linseed", kn: "ಅಗಸೆ" },
    agmarknetCommodity: "Linseed",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(5, 120),
    diseases: [foliar("linseed_rrust", "Rust", "ತುಕ್ಕು ರೋಗ", "Puccinia spp.",
      { months: RABI, humidityPct: 80, tempMinC: 5, tempMaxC: 20, wetDays: 2 },
      { en: "Propiconazole spray", kn: "ಪ್ರೊಪಿಕೊನಜೋಲ್ ಸಿಂಪರಣೆ", dryHours: 4, protectionDays: 21 }, 0.25)],
    yieldNote: "Rabi oilseed.",
  },
  {
    id: "jute",
    name: { en: "Jute", kn: "ಸೆಣಬು" },
    agmarknetCommodity: "Jute",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(25, 120),
    diseases: [foliar("jute_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Fibre, eastern India.",
  },
  {
    id: "tobacco",
    name: { en: "Tobacco", kn: "ಹೊಗೆಸೊಪ್ಪು" },
    agmarknetCommodity: "Tobacco",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(8, 120),
    diseases: [foliar("tobacco_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Cured leaf.",
  },
  {
    id: "tea",
    name: { en: "Tea", kn: "ಚಹಾ" },
    agmarknetCommodity: "Tea",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 4, qtlPerAcre: 4 }, { fromAge: 6, qtlPerAcre: 8 }, { fromAge: 8, qtlPerAcre: 10 }], 50, 0.2),
    diseases: [foliar("tea_blight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 30, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Made tea across many pluckings.",
  },
  {
    id: "rubber",
    name: { en: "Rubber", kn: "ರಬ್ಬರ್" },
    agmarknetCommodity: "Rubber",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 7, qtlPerAcre: 4 }, { fromAge: 10, qtlPerAcre: 7 }, { fromAge: 14, qtlPerAcre: 9 }], 30, 0.2),
    diseases: [foliar("rubber_phyto", "Phytophthora rot", "ಫೈಟೊಫ್ಥೊರಾ ಕೊಳೆ", "Phytophthora spp.",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 3 },
      { ...COPPER, dryHours: 5, protectionDays: 30 }, 0.3)],
    yieldNote: "Dry rubber sheet. Abnormal leaf fall is the monsoon threat.",
  },
  {
    id: "oil_palm",
    name: { en: "Oil palm", kn: "ಎಣ್ಣೆ ತಾಳೆ" },
    agmarknetCommodity: "Oil Palm",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 4, qtlPerAcre: 20 }, { fromAge: 7, qtlPerAcre: 60 }, { fromAge: 10, qtlPerAcre: 90 }], 30, 2),
    diseases: [foliar("oil_palm_phyto", "Phytophthora rot", "ಫೈಟೊಫ್ಥೊರಾ ಕೊಳೆ", "Phytophthora spp.",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 3 },
      { ...COPPER, dryHours: 5, protectionDays: 30 }, 0.3)],
    yieldNote: "Fresh fruit bunches.",
  },
  {
    id: "dry_chilli",
    name: { en: "Dry chilli", kn: "ಒಣ ಮೆಣಸಿನಕಾಯಿ" },
    agmarknetCommodity: "Dry Chillies",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(15, 180),
    diseases: [foliar("dry_chilli_anthrac", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    yieldNote: "Dry pods, roughly a quarter of green weight.",
  },
  {
    id: "coriander_seed",
    name: { en: "Coriander seed", kn: "ಕೊತ್ತಂಬರಿ ಬೀಜ" },
    agmarknetCommodity: "Coriander(Leaves)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(6, 110),
    diseases: [foliar("coriander_seed_rblight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 24, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rabi seed crop.",
  },
  {
    id: "coriander_leaves",
    name: { en: "Coriander leaves", kn: "ಕೊತ್ತಂಬರಿ ಸೊಪ್ಪು" },
    agmarknetCommodity: "Coriander(Leaves)",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(25, 45),
    diseases: [foliar("coriander_leaves_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Leafy crop, short cycle.",
  },
  {
    id: "cumin",
    name: { en: "Cumin", kn: "ಜೀರಿಗೆ" },
    agmarknetCommodity: "Cummin Seed(Jeera)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(3, 110),
    diseases: [foliar("cumin_rblight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 24, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Arid rabi spice.",
  },
  {
    id: "fenugreek",
    name: { en: "Fenugreek seed", kn: "ಮೆಂತ್ಯ" },
    agmarknetCommodity: "Methi Seeds",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(6, 120),
    diseases: [foliar("fenugreek_rblight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 24, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rabi seed spice.",
  },
  {
    id: "methi_leaves",
    name: { en: "Fenugreek leaves", kn: "ಮೆಂತ್ಯ ಸೊಪ್ಪು" },
    agmarknetCommodity: "Methi(Leaves)",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(25, 40),
    diseases: [foliar("methi_leaves_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Leafy crop, very short cycle.",
  },
  {
    id: "fennel",
    name: { en: "Fennel", kn: "ಸೋಂಪು" },
    agmarknetCommodity: "Fennel(Saunf)",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(6, 150),
    diseases: [foliar("fennel_rblight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 24, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rabi seed spice.",
  },
  {
    id: "garlic",
    name: { en: "Garlic", kn: "ಬೆಳ್ಳುಳ್ಳಿ" },
    agmarknetCommodity: "Garlic",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(50, 150),
    diseases: [foliar("garlic_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Cured bulbs.",
  },
  {
    id: "ajwain",
    name: { en: "Ajwain", kn: "ಓಮ" },
    agmarknetCommodity: "Ajwan",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(4, 140),
    diseases: [foliar("ajwain_rblight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: RABI, humidityPct: 85, tempMinC: 8, tempMaxC: 24, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Rabi seed spice.",
  },
  {
    id: "nutmeg",
    name: { en: "Nutmeg", kn: "ಜಾಯಿಕಾಯಿ" },
    agmarknetCommodity: "Nutmeg",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 6, qtlPerAcre: 1 }, { fromAge: 10, qtlPerAcre: 3 }, { fromAge: 15, qtlPerAcre: 4 }], 50, 0.1),
    diseases: [foliar("nutmeg_phyto", "Phytophthora rot", "ಫೈಟೊಫ್ಥೊರಾ ಕೊಳೆ", "Phytophthora spp.",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 3 },
      { ...COPPER, dryHours: 5, protectionDays: 30 }, 0.3)],
    yieldNote: "Dry nut and mace.",
  },
  {
    id: "clove",
    name: { en: "Clove", kn: "ಲವಂಗ" },
    agmarknetCommodity: "Cloves",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 7, qtlPerAcre: 0.5 }, { fromAge: 12, qtlPerAcre: 1.5 }, { fromAge: 18, qtlPerAcre: 2 }], 60, 0.05),
    diseases: [foliar("clove_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Dried buds.",
  },
  {
    id: "cinnamon",
    name: { en: "Cinnamon", kn: "ದಾಲ್ಚಿನ್ನಿ" },
    agmarknetCommodity: "Cinnamon(Dalchini)",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 3, qtlPerAcre: 1 }, { fromAge: 6, qtlPerAcre: 2.5 }, { fromAge: 10, qtlPerAcre: 3 }], 40, 0.1),
    diseases: [foliar("cinnamon_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Dried quills.",
  },
  {
    id: "tamarind",
    name: { en: "Tamarind", kn: "ಹುಣಸೆಹಣ್ಣು" },
    agmarknetCommodity: "Tamarind Fruit",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 8, qtlPerAcre: 8 }, { fromAge: 12, qtlPerAcre: 15 }, { fromAge: 20, qtlPerAcre: 20 }], 60, 0.3),
    diseases: [foliar("tamarind_anthrac", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    yieldNote: "Mature trees, alternate bearing.",
  },
  {
    id: "guava",
    name: { en: "Guava", kn: "ಸೀಬೆಕಾಯಿ" },
    agmarknetCommodity: "Guava",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 3, qtlPerAcre: 25 }, { fromAge: 5, qtlPerAcre: 50 }, { fromAge: 8, qtlPerAcre: 65 }], 30, 2),
    diseases: [foliar("guava_anthrac", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    yieldNote: "Two crops a year in many areas.",
  },
  {
    id: "orange",
    name: { en: "Orange / mandarin", kn: "ಕಿತ್ತಳೆ" },
    agmarknetCommodity: "Orange",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 4, qtlPerAcre: 25 }, { fromAge: 8, qtlPerAcre: 55 }, { fromAge: 12, qtlPerAcre: 70 }], 30, 2),
    diseases: [foliar("orange_bact", "Bacterial blight", "ಬ್ಯಾಕ್ಟೀರಿಯಾ ಅಂಗಮಾರಿ", "Xanthomonas spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 34, wetDays: 2 },
      { ...COPPER, dryHours: 4, protectionDays: 15 }, 0.3)],
    yieldNote: "Citrus canker is the wet-season threat.",
  },
  {
    id: "sweet_lime",
    name: { en: "Sweet lime / mosambi", kn: "ಮೂಸಂಬಿ" },
    agmarknetCommodity: "Mousambi(Sweet Lime)",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 4, qtlPerAcre: 25 }, { fromAge: 8, qtlPerAcre: 55 }, { fromAge: 12, qtlPerAcre: 70 }], 30, 2),
    diseases: [foliar("sweet_lime_bact", "Bacterial blight", "ಬ್ಯಾಕ್ಟೀರಿಯಾ ಅಂಗಮಾರಿ", "Xanthomonas spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 34, wetDays: 2 },
      { ...COPPER, dryHours: 4, protectionDays: 15 }, 0.3)],
    yieldNote: "Citrus canker is the wet-season threat.",
  },
  {
    id: "lemon",
    name: { en: "Lemon", kn: "ನಿಂಬೆಹಣ್ಣು" },
    agmarknetCommodity: "Lemon",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 3, qtlPerAcre: 20 }, { fromAge: 6, qtlPerAcre: 45 }, { fromAge: 10, qtlPerAcre: 55 }], 30, 1.5),
    diseases: [foliar("lemon_bact", "Bacterial blight", "ಬ್ಯಾಕ್ಟೀರಿಯಾ ಅಂಗಮಾರಿ", "Xanthomonas spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 34, wetDays: 2 },
      { ...COPPER, dryHours: 4, protectionDays: 15 }, 0.3)],
    yieldNote: "Bears through much of the year.",
  },
  {
    id: "jackfruit",
    name: { en: "Jackfruit", kn: "ಹಲಸಿನಕಾಯಿ" },
    agmarknetCommodity: "Jack Fruit",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 6, qtlPerAcre: 30 }, { fromAge: 10, qtlPerAcre: 70 }, { fromAge: 15, qtlPerAcre: 90 }], 50, 1),
    diseases: [foliar("jackfruit_phyto", "Phytophthora rot", "ಫೈಟೊಫ್ಥೊರಾ ಕೊಳೆ", "Phytophthora spp.",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 3 },
      { ...COPPER, dryHours: 5, protectionDays: 30 }, 0.3)],
    yieldNote: "Very large fruit; yield varies hugely by tree.",
  },
  {
    id: "pineapple",
    name: { en: "Pineapple", kn: "ಅನಾನಸ್" },
    agmarknetCommodity: "Pineapple",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(150, 450),
    diseases: [foliar("pineapple_phyto", "Phytophthora rot", "ಫೈಟೊಫ್ಥೊರಾ ಕೊಳೆ", "Phytophthora spp.",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 3 },
      { ...COPPER, dryHours: 5, protectionDays: 30 }, 0.3)],
    yieldNote: "One long cycle from sucker to fruit.",
  },
  {
    id: "muskmelon",
    name: { en: "Muskmelon", kn: "ಕರಬೂಜ" },
    agmarknetCommodity: "Water Melon",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(90, 90),
    diseases: [foliar("muskmelon_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Summer crop on drip.",
  },
  {
    id: "apple",
    name: { en: "Apple", kn: "Apple" },
    agmarknetCommodity: "Apple",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 5, qtlPerAcre: 20 }, { fromAge: 8, qtlPerAcre: 60 }, { fromAge: 12, qtlPerAcre: 90 }], 35, 2),
    diseases: [foliar("apple_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Temperate hill orchards.",
  },
  {
    id: "pear",
    name: { en: "Pear", kn: "Pear" },
    agmarknetCommodity: "Pear(Marasebu)",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 5, qtlPerAcre: 20 }, { fromAge: 8, qtlPerAcre: 55 }, { fromAge: 12, qtlPerAcre: 80 }], 35, 2),
    diseases: [foliar("pear_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Temperate hill orchards.",
  },
  {
    id: "peach",
    name: { en: "Peach", kn: "Peach" },
    agmarknetCommodity: "Peach",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 3, qtlPerAcre: 15 }, { fromAge: 6, qtlPerAcre: 40 }, { fromAge: 10, qtlPerAcre: 55 }], 20, 3),
    diseases: [foliar("peach_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Temperate hill orchards.",
  },
  {
    id: "plum",
    name: { en: "Plum", kn: "Plum" },
    agmarknetCommodity: "Plum",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 3, qtlPerAcre: 12 }, { fromAge: 6, qtlPerAcre: 35 }, { fromAge: 10, qtlPerAcre: 45 }], 20, 2),
    diseases: [foliar("plum_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Temperate hill orchards.",
  },
  {
    id: "litchi",
    name: { en: "Litchi", kn: "Litchi" },
    agmarknetCommodity: "Litchi",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 5, qtlPerAcre: 10 }, { fromAge: 10, qtlPerAcre: 35 }, { fromAge: 15, qtlPerAcre: 50 }], 40, 1),
    diseases: [foliar("litchi_anthrac", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    yieldNote: "Strongly alternate bearing.",
  },
  {
    id: "ber",
    name: { en: "Ber", kn: "ಬೋರೆಹಣ್ಣು" },
    agmarknetCommodity: "Ber(Zizyphus/Borehannu)",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 3, qtlPerAcre: 20 }, { fromAge: 5, qtlPerAcre: 45 }, { fromAge: 8, qtlPerAcre: 60 }], 25, 2),
    diseases: [foliar("ber_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Arid-zone fruit.",
  },
  {
    id: "custard_apple",
    name: { en: "Custard apple", kn: "ಸೀತಾಫಲ" },
    agmarknetCommodity: "Custard Apple (Sharifa)",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 4, qtlPerAcre: 10 }, { fromAge: 7, qtlPerAcre: 25 }, { fromAge: 10, qtlPerAcre: 32 }], 25, 1),
    diseases: [foliar("custard_apple_anthrac", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    yieldNote: "Rainfed orchards.",
  },
  {
    id: "fig",
    name: { en: "Fig", kn: "ಅಂಜೂರ" },
    agmarknetCommodity: "Fig(Anjura/Anjeer)",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 2, qtlPerAcre: 15 }, { fromAge: 4, qtlPerAcre: 40 }, { fromAge: 7, qtlPerAcre: 55 }], 20, 2),
    diseases: [foliar("fig_rust", "Rust", "ತುಕ್ಕು ರೋಗ", "Puccinia spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 28, wetDays: 3 },
      { en: "Propiconazole spray", kn: "ಪ್ರೊಪಿಕೊನಜೋಲ್ ಸಿಂಪರಣೆ", dryHours: 4, protectionDays: 21 }, 0.25)],
    yieldNote: "Bears young.",
  },
  {
    id: "amla",
    name: { en: "Amla", kn: "ನೆಲ್ಲಿಕಾಯಿ" },
    agmarknetCommodity: "Amla(Nelli Kai)",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 4, qtlPerAcre: 15 }, { fromAge: 8, qtlPerAcre: 50 }, { fromAge: 12, qtlPerAcre: 70 }], 40, 1),
    diseases: [foliar("amla_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Hardy, low input.",
  },
  {
    id: "strawberry",
    name: { en: "Strawberry", kn: "Strawberry" },
    agmarknetCommodity: "Straw Berry",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(60, 120),
    diseases: [foliar("strawberry_anthrac", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    yieldNote: "Hill and protected cultivation.",
  },
  {
    id: "mulberry",
    name: { en: "Mulberry", kn: "ಹಿಪ್ಪುನೇರಳೆ" },
    agmarknetCommodity: "Mulberry",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 1, qtlPerAcre: 80 }, { fromAge: 2, qtlPerAcre: 140 }, { fromAge: 3, qtlPerAcre: 180 }], 15, 10),
    diseases: [foliar("mulberry_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Leaf for sericulture, many cuts a year.",
  },
  {
    id: "radish",
    name: { en: "Radish", kn: "ಮೂಲಂಗಿ" },
    agmarknetCommodity: "Raddish",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(60, 55),
    diseases: [foliar("radish_blight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 30, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Very short cycle.",
  },
  {
    id: "beetroot",
    name: { en: "Beetroot", kn: "ಬೀಟ್‌ರೂಟ್" },
    agmarknetCommodity: "Beetroot",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(70, 90),
    diseases: [foliar("beetroot_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Roots at commercial spacing.",
  },
  {
    id: "spinach",
    name: { en: "Spinach", kn: "ಪಾಲಕ್" },
    agmarknetCommodity: "Spinach",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(40, 45),
    diseases: [foliar("spinach_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Leafy crop, multiple cuts.",
  },
  {
    id: "amaranthus",
    name: { en: "Amaranthus", kn: "ಹರಿವೆ ಸೊಪ್ಪು" },
    agmarknetCommodity: "Amaranthus",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(35, 40),
    diseases: [foliar("amaranthus_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Leafy crop, very short cycle.",
  },
  {
    id: "capsicum",
    name: { en: "Capsicum", kn: "ದೊಣ್ಣೆ ಮೆಣಸಿನಕಾಯಿ" },
    agmarknetCommodity: "Capsicum",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(70, 130),
    diseases: [foliar("capsicum_anthrac", "Anthracnose", "ಆಂಥ್ರಾಕ್ನೋಸ್", "Colletotrichum spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.3)],
    yieldNote: "Higher under protected cultivation.",
  },
  {
    id: "bitter_gourd",
    name: { en: "Bitter gourd", kn: "ಹಾಗಲಕಾಯಿ" },
    agmarknetCommodity: "Bitter gourd",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(60, 90),
    diseases: [foliar("bitter_gourd_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Across pickings on a trellis.",
  },
  {
    id: "bottle_gourd",
    name: { en: "Bottle gourd", kn: "ಸೋರೆಕಾಯಿ" },
    agmarknetCommodity: "Bottle gourd",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(80, 90),
    diseases: [foliar("bottle_gourd_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Across pickings.",
  },
  {
    id: "ridge_gourd",
    name: { en: "Ridge gourd", kn: "ಹೀರೆಕಾಯಿ" },
    agmarknetCommodity: "Ridgeguard(Tori)",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(60, 90),
    diseases: [foliar("ridge_gourd_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Across pickings.",
  },
  {
    id: "snake_gourd",
    name: { en: "Snake gourd", kn: "ಪಡವಲಕಾಯಿ" },
    agmarknetCommodity: "Snakeguard",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(60, 90),
    diseases: [foliar("snake_gourd_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Across pickings.",
  },
  {
    id: "ash_gourd",
    name: { en: "Ash gourd", kn: "ಬೂದುಗುಂಬಳ" },
    agmarknetCommodity: "Ashgourd",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(90, 110),
    diseases: [foliar("ash_gourd_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Stores well after harvest.",
  },
  {
    id: "pumpkin",
    name: { en: "Pumpkin", kn: "ಕುಂಬಳಕಾಯಿ" },
    agmarknetCommodity: "Pumpkin",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(90, 100),
    diseases: [foliar("pumpkin_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Stores well after harvest.",
  },
  {
    id: "sweet_potato",
    name: { en: "Sweet potato", kn: "ಸಿಹಿ ಗೆಣಸು" },
    agmarknetCommodity: "Sweet Potato",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(80, 120),
    diseases: [foliar("sweet_potato_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Tubers.",
  },
  {
    id: "colocasia",
    name: { en: "Colocasia", kn: "ಕೆಸು" },
    agmarknetCommodity: "Colacasia",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(70, 180),
    diseases: [foliar("colocasia_phyto", "Phytophthora rot", "ಫೈಟೊಫ್ಥೊರಾ ಕೊಳೆ", "Phytophthora spp.",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 3 },
      { ...COPPER, dryHours: 5, protectionDays: 30 }, 0.3)],
    yieldNote: "Leaf blight follows monsoon waterlogging.",
  },
  {
    id: "elephant_yam",
    name: { en: "Elephant foot yam", kn: "ಸುವರ್ಣಗಡ್ಡೆ" },
    agmarknetCommodity: "Elephant Yam (Suran)",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(120, 240),
    diseases: [foliar("elephant_yam_phyto", "Phytophthora rot", "ಫೈಟೊಫ್ಥೊರಾ ಕೊಳೆ", "Phytophthora spp.",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 3 },
      { ...COPPER, dryHours: 5, protectionDays: 30 }, 0.3)],
    yieldNote: "Corms; heavy yielder.",
  },
  {
    id: "tapioca",
    name: { en: "Tapioca / cassava", kn: "ಮರಗೆಣಸು" },
    agmarknetCommodity: "Tapioca",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(120, 300),
    diseases: [foliar("tapioca_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Tubers, long duration.",
  },
  {
    id: "drumstick",
    name: { en: "Drumstick", kn: "ನುಗ್ಗೆಕಾಯಿ" },
    agmarknetCommodity: "Drumstick",
    grades: [],
    irrigation: { intervalDays: ORCHARD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 1, qtlPerAcre: 25 }, { fromAge: 2, qtlPerAcre: 55 }, { fromAge: 4, qtlPerAcre: 70 }], 15, 4),
    diseases: [foliar("drumstick_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Annual types bear in the first year.",
  },
  {
    id: "knol_khol",
    name: { en: "Knol khol", kn: "ನವಿಲುಕೋಸು" },
    agmarknetCommodity: "Knol Khol",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(70, 80),
    diseases: [foliar("knol_khol_bact", "Bacterial blight", "ಬ್ಯಾಕ್ಟೀರಿಯಾ ಅಂಗಮಾರಿ", "Xanthomonas spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 20, tempMaxC: 34, wetDays: 2 },
      { ...COPPER, dryHours: 4, protectionDays: 15 }, 0.3)],
    yieldNote: "Short-cycle cole crop.",
  },
  {
    id: "turnip",
    name: { en: "Turnip", kn: "ಟರ್ನಿಪ್" },
    agmarknetCommodity: "Turnip",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(70, 80),
    diseases: [foliar("turnip_blight", "Leaf blight", "ಎಲೆ ಒಣಗು ರೋಗ", "Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 30, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 15 }, 0.25)],
    yieldNote: "Cool-season root.",
  },
  {
    id: "broccoli",
    name: { en: "Broccoli", kn: "ಬ್ರೊಕೊಲಿ" },
    agmarknetCommodity: "Broccoli",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(50, 90),
    diseases: [foliar("broccoli_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Cool-season, premium market.",
  },
  {
    id: "lettuce",
    name: { en: "Lettuce", kn: "ಲೆಟ್ಯೂಸ್" },
    agmarknetCommodity: "Lettuce",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(50, 70),
    diseases: [foliar("lettuce_downy", "Downy mildew", "ಡೌನಿ ಶಿಲೀಂಧ್ರ", "Pseudoperonospora/Peronospora spp.",
      { months: MONSOON, humidityPct: 88, tempMinC: 18, tempMaxC: 30, wetDays: 2 },
      { ...MANCOZEB, dryHours: 3, protectionDays: 10 }, 0.35)],
    yieldNote: "Cool-season leafy crop.",
  },
  {
    id: "betel_leaves",
    name: { en: "Betel leaves", kn: "ವೀಳ್ಯದೆಲೆ" },
    agmarknetCommodity: "Betal Leaves",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 1, qtlPerAcre: 20 }, { fromAge: 2, qtlPerAcre: 35 }, { fromAge: 3, qtlPerAcre: 45 }], 10, 3),
    diseases: [foliar("betel_leaves_phyto", "Phytophthora rot", "ಫೈಟೊಫ್ಥೊರಾ ಕೊಳೆ", "Phytophthora spp.",
      { months: MONSOON, humidityPct: 90, tempMinC: 20, tempMaxC: 30, wetDays: 3 },
      { ...COPPER, dryHours: 5, protectionDays: 30 }, 0.3)],
    yieldNote: "Leaf rot follows monsoon waterlogging; sold by count, so weight is approximate.",
  },
  {
    id: "lemongrass",
    name: { en: "Lemongrass", kn: "ಮಜ್ಜಿಗೆ ಹುಲ್ಲು" },
    agmarknetCommodity: "Lemon Grass",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 1, qtlPerAcre: 80 }, { fromAge: 2, qtlPerAcre: 140 }, { fromAge: 3, qtlPerAcre: 160 }], 8, 20),
    diseases: [foliar("lemongrass_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Herbage for oil distillation, several cuts a year.",
  },
  {
    id: "mint",
    name: { en: "Mint", kn: "ಪುದೀನ" },
    agmarknetCommodity: "Mint(Pudina)",
    grades: [],
    irrigation: { intervalDays: VEG, rainSkipMm: 10 },
    yield: seasonal(60, 90),
    diseases: [foliar("mint_rust", "Rust", "ತುಕ್ಕು ರೋಗ", "Puccinia spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 28, wetDays: 3 },
      { en: "Propiconazole spray", kn: "ಪ್ರೊಪಿಕೊನಜೋಲ್ ಸಿಂಪರಣೆ", dryHours: 4, protectionDays: 21 }, 0.25)],
    yieldNote: "Several cuts per planting.",
  },
  {
    id: "aloe_vera",
    name: { en: "Aloe vera", kn: "ಲೋಳೆಸರ" },
    agmarknetCommodity: "Aloe Vera",
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: perennial([{ fromAge: 1, qtlPerAcre: 60 }, { fromAge: 2, qtlPerAcre: 120 }, { fromAge: 3, qtlPerAcre: 150 }], 8, 15),
    diseases: [foliar("aloe_vera_leafspot", "Leaf spot", "ಎಲೆ ಚುಕ್ಕೆ ರೋಗ", "Cercospora/Alternaria spp.",
      { months: MONSOON, humidityPct: 85, tempMinC: 18, tempMaxC: 32, wetDays: 3 },
      { ...MANCOZEB, dryHours: 4, protectionDays: 14 }, 0.25)],
    yieldNote: "Leaf weight; low input.",
  },
];

/**
 * Fallback for a commodity with no agronomy in the registry.
 *
 * This is now reached only by an id the registry does not know — a farm saved
 * before a rename, or corrupted storage. The irrigation interval is a generic
 * default and the yield is zero rather than a guess, so the app reports what it
 * does not know instead of inventing it. Every real crop lives in CROPS.
 */
export function genericCrop(id: string, en: string, kn: string, commodity: string): CropConfig {
  return {
    id,
    name: { en, kn },
    agmarknetCommodity: commodity,
    grades: [],
    irrigation: { intervalDays: FIELD, rainSkipMm: 10 },
    yield: seasonal(0, 120),
    diseases: [],
  };
}
